# frozen_string_literal: true

GroupsMetadataTeamsCommittees.create!(friendly_id: 'wct', email: 'communication@worldcubeassociation.org')
GroupsMetadataTeamsCommittees.create!(friendly_id: 'wrt', email: 'results@worldcubeassociation.org')
GroupsMetadataTeamsCommittees.create!(friendly_id: 'wst', email: 'software@worldcubeassociation.org')
GroupsMetadataTeamsCommittees.create!(friendly_id: 'weat', email: 'assistants@worldcubeassociation.org')
GroupsMetadataTeamsCommittees.create!(friendly_id: 'wfc', email: 'finance@worldcubeassociation.org')
GroupsMetadataTeamsCommittees.create!(friendly_id: 'wcat', email: 'competitions@worldcubeassociation.org')
GroupsMetadataTeamsCommittees.create!(friendly_id: 'wdc', email: 'disciplinary@worldcubeassociation.org')
GroupsMetadataTeamsCommittees.create!(friendly_id: 'wec', email: 'ethics@worldcubeassociation.org')
GroupsMetadataTeamsCommittees.create!(friendly_id: 'wmt', email: 'marketing@worldcubeassociation.org')
GroupsMetadataTeamsCommittees.create!(friendly_id: 'wqac', email: 'quality@worldcubeassociation.org')
GroupsMetadataTeamsCommittees.create!(friendly_id: 'wrc', email: 'regulations@worldcubeassociation.org')
GroupsMetadataTeamsCommittees.create!(friendly_id: 'wsot', email: 'sports@worldcubeassociation.org')
GroupsMetadataTeamsCommittees.create!(friendly_id: 'wat', email: 'archive@worldcubeassociation.org')
