/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Background and accent color of this box
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColorPaletteSelect".
 */
export type ColorPaletteSelect = 'blue' | 'red' | 'green' | 'orange' | 'yellow' | 'wcaWhite';
/**
 * Icon name
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconName".
 */
export type IconName =
  | 'About the Regulations'
  | 'About the WCA'
  | 'Admin Results'
  | 'All Competitions'
  | 'Bookmark'
  | 'Clone'
  | 'Competition Not Started'
  | 'Registration Closed'
  | 'Registration Closed (Red)'
  | 'Registration Full but Open'
  | 'Registration Full but Open (Orange)'
  | 'Registration Not Full, Open'
  | 'Registration Not Full, Open (Green)'
  | 'Registration Not Open Yet'
  | 'Registration Not Open Yet (Grey)'
  | 'Registration Open Date'
  | 'Registration Close Date'
  | 'Competitors'
  | 'Contact'
  | 'Delegate Report'
  | 'Details'
  | 'Developer Export'
  | 'Disciplinary Log'
  | 'Disclaimer'
  | 'Download'
  | 'Edit'
  | 'Educational Resources'
  | 'Error'
  | 'External Link'
  | 'Facebook'
  | 'Filters'
  | 'GitHub'
  | 'Guidelines'
  | 'Help and FAQs'
  | 'Incidents Log'
  | 'Information'
  | 'Instagram'
  | 'Language'
  | 'List'
  | 'Location'
  | 'Manage Tabs'
  | 'Map'
  | 'Media Submission'
  | 'Menu'
  | 'Multimedia'
  | 'My Competitions'
  | 'My Results'
  | 'National Championship'
  | 'New Competition'
  | 'On-the-Spot Registration'
  | 'Payment'
  | 'Privacy'
  | 'Rankings'
  | 'Records'
  | 'Regional Organisations'
  | 'Register'
  | 'Registration'
  | 'Regulations and Guidelines'
  | 'Regulations History'
  | 'Regulations'
  | 'Results Export'
  | 'Scrambles'
  | 'Search'
  | 'Spectators'
  | 'Speedcubing History'
  | 'Spots Left'
  | 'Statistics'
  | 'Teams, Committees and Councils'
  | 'Tools'
  | 'Translators'
  | 'Twitch'
  | 'User'
  | 'Users / Persons'
  | 'Venue'
  | 'WCA Delegates'
  | 'WCA Documents'
  | 'WCA Live'
  | 'WCA Logo'
  | 'WCA Officers and Board'
  | 'Weibo'
  | 'X (formerly Twitter)'
  | 'YouTube'
  | '222Icon'
  | '333bfIcon'
  | '333fmIcon'
  | '333ftIcon'
  | '333Icon'
  | '333mbfIcon'
  | '333ohIcon'
  | '333mboIcon'
  | '444bfIcon'
  | '444Icon'
  | '555bfIcon'
  | '555Icon'
  | '666Icon'
  | '777Icon'
  | 'ClockIcon'
  | 'FtoIcon'
  | 'MagicIcon'
  | 'MinxIcon'
  | 'MmagicIcon'
  | 'PyramIcon'
  | 'SkewbIcon'
  | 'Sq1Icon';
/**
 * Page on this website the link points to.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StaticTargetLink".
 */
export type StaticTargetLink =
  | '/'
  | '/about'
  | '/competitions'
  | '/delegates'
  | '/disclaimer'
  | '/documents'
  | '/export/developer'
  | '/export/results'
  | '/faq'
  | '/incidents'
  | '/logo'
  | '/officers-and-board'
  | '/organizations'
  | '/privacy'
  | '/regulations/about'
  | '/regulations/history'
  | '/regulations/scrambles'
  | '/regulations/translations'
  | '/results/rankings'
  | '/results/records'
  | '/score-tools'
  | '/speedcubing-history'
  | '/teams-committees'
  | '/translators';
/**
 * What to do when one column ends up shorter than the other.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GrowthStrategy".
 */
export type GrowthStrategy = ('grow' | 'justify') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    testimonials: Testimonial;
    announcements: Announcement;
    faqCategories: FaqCategory;
    faqQuestions: FaqQuestion;
    users: User;
    documents: Document;
    regulationsHistoryItem: RegulationsHistoryItem;
    tools: Tool;
    sessions: Session;
    accounts: Account;
    verifications: Verification;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    faqCategories: {
      relatedQuestions: 'faqQuestions';
    };
  };
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    faqCategories: FaqCategoriesSelect<false> | FaqCategoriesSelect<true>;
    faqQuestions: FaqQuestionsSelect<false> | FaqQuestionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    regulationsHistoryItem: RegulationsHistoryItemSelect<false> | RegulationsHistoryItemSelect<true>;
    tools: ToolsSelect<false> | ToolsSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    verifications: VerificationsSelect<false> | VerificationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | (
        | 'en'
        | 'ca'
        | 'cs'
        | 'da'
        | 'de'
        | 'eo'
        | 'es-ES'
        | 'es-419'
        | 'eu'
        | 'fi'
        | 'fr'
        | 'fr-CA'
        | 'hr'
        | 'hu'
        | 'id'
        | 'it'
        | 'ja'
        | 'kk'
        | 'ko'
        | 'nl'
        | 'pl'
        | 'pt'
        | 'pt-BR'
        | 'ro'
        | 'ru'
        | 'sk'
        | 'sl'
        | 'sv'
        | 'th'
        | 'uk'
        | 'vi'
        | 'zh-CN'
        | 'zh-TW'
      )
    | (
        | 'en'
        | 'ca'
        | 'cs'
        | 'da'
        | 'de'
        | 'eo'
        | 'es-ES'
        | 'es-419'
        | 'eu'
        | 'fi'
        | 'fr'
        | 'fr-CA'
        | 'hr'
        | 'hu'
        | 'id'
        | 'it'
        | 'ja'
        | 'kk'
        | 'ko'
        | 'nl'
        | 'pl'
        | 'pt'
        | 'pt-BR'
        | 'ro'
        | 'ru'
        | 'sk'
        | 'sl'
        | 'sv'
        | 'th'
        | 'uk'
        | 'vi'
        | 'zh-CN'
        | 'zh-TW'
      )[];
  globals: {
    nav: Nav;
    footer: Footer;
    'social-links': SocialLink;
    home: Home;
    'about-us-page': AboutUsPage;
    'privacy-page': PrivacyPage;
    'disclaimer-page': DisclaimerPage;
    'speedcubing-history-page': SpeedcubingHistoryPage;
    'about-regulations-page': AboutRegulationsPage;
    'documents-page': DocumentsPage;
    'faq-page': FaqPage;
    'logo-page': LogoPage;
  };
  globalsSelect: {
    nav: NavSelect<false> | NavSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'social-links': SocialLinksSelect<false> | SocialLinksSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    'about-us-page': AboutUsPageSelect<false> | AboutUsPageSelect<true>;
    'privacy-page': PrivacyPageSelect<false> | PrivacyPageSelect<true>;
    'disclaimer-page': DisclaimerPageSelect<false> | DisclaimerPageSelect<true>;
    'speedcubing-history-page': SpeedcubingHistoryPageSelect<false> | SpeedcubingHistoryPageSelect<true>;
    'about-regulations-page': AboutRegulationsPageSelect<false> | AboutRegulationsPageSelect<true>;
    'documents-page': DocumentsPageSelect<false> | DocumentsPageSelect<true>;
    'faq-page': FaqPageSelect<false> | FaqPageSelect<true>;
    'logo-page': LogoPageSelect<false> | LogoPageSelect<true>;
  };
  locale:
    | 'en'
    | 'ca'
    | 'cs'
    | 'da'
    | 'de'
    | 'eo'
    | 'es-ES'
    | 'es-419'
    | 'eu'
    | 'fi'
    | 'fr'
    | 'fr-CA'
    | 'hr'
    | 'hu'
    | 'id'
    | 'it'
    | 'ja'
    | 'kk'
    | 'ko'
    | 'nl'
    | 'pl'
    | 'pt'
    | 'pt-BR'
    | 'ro'
    | 'ru'
    | 'sk'
    | 'sl'
    | 'sv'
    | 'th'
    | 'uk'
    | 'vi'
    | 'zh-CN'
    | 'zh-TW';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alternative text describing the image, read out by screen readers and shown when the image cannot load.
   */
  alt: string;
  /**
   * Optional. If set, the image becomes a link to this URL wherever it is rendered.
   */
  customLink?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  /**
   * Picture of the person being quoted.
   */
  image?: (string | null) | Media;
  /**
   * Short pull quote shown on the testimonials spinner before the full testimonial is opened.
   */
  punchline: string;
  /**
   * The complete testimonial in the person's own words.
   */
  fullTestimonial: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  fullTestimonialMarkdown?: string | null;
  /**
   * Name of the person being quoted.
   */
  whoDunnit: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: string;
  /**
   * Header image shown next to the announcement on the announcements list and at the top of the announcement itself.
   */
  image?: (string | null) | Media;
  /**
   * Headline of the announcement, shown on the announcements list and as the page title.
   */
  title: string;
  /**
   * Shown on the announcements list before 'Read More'. Falls back to the beginning of the content when empty.
   */
  summary?: string | null;
  /**
   * Full body of the announcement.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  contentMarkdown?: string | null;
  /**
   * Date the announcement was published, used to sort the announcements list.
   */
  publishedAt: string;
  /**
   * WCA user credited as the author of the announcement.
   */
  publishedBy: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  /**
   * Payload's own identifier for this user.
   */
  id: string;
  /**
   * Display name of the user, as Rails knows them.
   */
  name?: string | null;
  roles?: string[];
  /**
   * Auto-added by Better Auth (email)
   */
  email: string;
  /**
   * Auto-added by Better Auth (emailVerified)
   */
  emailVerified: boolean;
  /**
   * Auto-added by Better Auth (image)
   */
  image?: string | null;
  /**
   * Auto-added by Better Auth (wcaId)
   */
  wcaId?: string | null;
  /**
   * Auto-added by Better Auth (wcaUserId)
   */
  wcaUserId?: number | null;
  updatedAt: string;
  createdAt: string;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqCategories".
 */
export interface FaqCategory {
  id: string;
  /**
   * Name of the category, shown as the heading above its questions on the FAQ page.
   */
  title: string;
  colorPalette: ColorPaletteSelect;
  /**
   * Questions that point at this category. Filled in automatically, edit the question to change it.
   */
  relatedQuestions?: {
    docs?: (string | FaqQuestion)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqQuestions".
 */
export interface FaqQuestion {
  id: string;
  /**
   * Category this question is grouped under on the FAQ page.
   */
  category: string | FaqCategory;
  /**
   * The question as asked, shown as the clickable heading of the FAQ entry.
   */
  question: string;
  /**
   * Plain text answer. Used when the rich text answer below is empty.
   */
  answer: string;
  /**
   * Formatted answer. Takes precedence over the plain text answer above.
   */
  answerRichtext?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  answerRichtextMarkdown?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: string;
  /**
   * Name of the document, shown as the link text.
   */
  title: string;
  icon: IconName;
  /**
   * URL the document links to.
   */
  link: string;
  /**
   * Category name (used for grouping documents)
   */
  category?: ('motions' | 'minutes' | 'policies' | 'finances') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulationsHistoryItem".
 */
export interface RegulationsHistoryItem {
  id: string;
  /**
   * Version identifier of this Regulations release, for example '2024'.
   */
  version: string;
  /**
   * URL of the Regulations at this version.
   */
  url: string;
  /**
   * Optional. URL of the full list of changes introduced by this version.
   */
  changesUrl?: string | null;
  /**
   * Optional. URL of the summary of changes introduced by this version.
   */
  summarizedChangesUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools".
 */
export interface Tool {
  id: string;
  /**
   * Name of the tool, as its authors spell it.
   */
  name: string;
  /**
   * One line explaining what the tool does, shown on its card on the score tools page.
   */
  description: string;
  /**
   * URL of the tool's homepage.
   */
  homepageLink: string;
  /**
   * Optional. URL of a guide on how to use the tool.
   */
  guideLink?: string | null;
  /**
   * Optional. URL of the tool's source code repository.
   */
  sourceCodeLink?: string | null;
  /**
   * Whether this tool is maintained by the WCA.
   */
  isOfficial?: boolean | null;
  /**
   * Name of the person or team that maintains the tool.
   */
  author: string;
  /**
   * Stage of a competition the tool is used in, used to group the tools.
   */
  category: 'before' | 'during' | 'after';
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-generated from Better Auth schema (session)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: string;
  expiresAt: string;
  token: string;
  ipAddress?: string | null;
  userAgent?: string | null;
  user: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-generated from Better Auth schema (account)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: string;
  issuer: string;
  accountId: string;
  providerId: string;
  user: string | User;
  accessToken?: string | null;
  refreshToken?: string | null;
  idToken?: string | null;
  accessTokenExpiresAt?: string | null;
  refreshTokenExpiresAt?: string | null;
  scope?: string | null;
  password?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-generated from Better Auth schema (verification)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications".
 */
export interface Verification {
  id: string;
  identifier: string;
  value: string;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'announcements';
        value: string | Announcement;
      } | null)
    | ({
        relationTo: 'faqCategories';
        value: string | FaqCategory;
      } | null)
    | ({
        relationTo: 'faqQuestions';
        value: string | FaqQuestion;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'documents';
        value: string | Document;
      } | null)
    | ({
        relationTo: 'regulationsHistoryItem';
        value: string | RegulationsHistoryItem;
      } | null)
    | ({
        relationTo: 'tools';
        value: string | Tool;
      } | null)
    | ({
        relationTo: 'sessions';
        value: string | Session;
      } | null)
    | ({
        relationTo: 'accounts';
        value: string | Account;
      } | null)
    | ({
        relationTo: 'verifications';
        value: string | Verification;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  customLink?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  image?: T;
  punchline?: T;
  fullTestimonial?: T;
  fullTestimonialMarkdown?: T;
  whoDunnit?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  image?: T;
  title?: T;
  summary?: T;
  content?: T;
  contentMarkdown?: T;
  publishedAt?: T;
  publishedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqCategories_select".
 */
export interface FaqCategoriesSelect<T extends boolean = true> {
  title?: T;
  colorPalette?: T;
  relatedQuestions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqQuestions_select".
 */
export interface FaqQuestionsSelect<T extends boolean = true> {
  category?: T;
  question?: T;
  answer?: T;
  answerRichtext?: T;
  answerRichtextMarkdown?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  roles?: T;
  email?: T;
  emailVerified?: T;
  image?: T;
  wcaId?: T;
  wcaUserId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  icon?: T;
  link?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulationsHistoryItem_select".
 */
export interface RegulationsHistoryItemSelect<T extends boolean = true> {
  version?: T;
  url?: T;
  changesUrl?: T;
  summarizedChangesUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools_select".
 */
export interface ToolsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  homepageLink?: T;
  guideLink?: T;
  sourceCodeLink?: T;
  isOfficial?: T;
  author?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  expiresAt?: T;
  token?: T;
  ipAddress?: T;
  userAgent?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  issuer?: T;
  accountId?: T;
  providerId?: T;
  user?: T;
  accessToken?: T;
  refreshToken?: T;
  idToken?: T;
  accessTokenExpiresAt?: T;
  refreshTokenExpiresAt?: T;
  scope?: T;
  password?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications_select".
 */
export interface VerificationsSelect<T extends boolean = true> {
  identifier?: T;
  value?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav".
 */
export interface Nav {
  id: string;
  /**
   * The top level entries of the navigation, left to right.
   */
  entry: (
    | {
        /**
         * Label of the dropdown in the top level navigation.
         */
        title: string;
        displayIcon?: IconName;
        /**
         * Links and submenus inside this dropdown.
         */
        entries: (
          | {
              /**
               * Link text shown in the navigation.
               */
              displayText: string;
              targetLink: StaticTargetLink;
              displayIcon?: IconName;
              id?: string | null;
              blockName?: string | null;
              blockType: 'LinkItem';
            }
          | {
              /**
               * Link text shown in the navigation.
               */
              displayText: string;
              /**
               * URL outside this website the link points to.
               */
              targetLink: string;
              displayIcon?: IconName;
              id?: string | null;
              blockName?: string | null;
              blockType: 'ExternalLinkItem';
            }
          | {
              /**
               * Label of the submenu inside the dropdown.
               */
              title: string;
              displayIcon?: IconName;
              /**
               * Links inside this submenu.
               */
              entries: (
                | {
                    /**
                     * Link text shown in the navigation.
                     */
                    displayText: string;
                    targetLink: StaticTargetLink;
                    displayIcon?: IconName;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'LinkItem';
                  }
                | {
                    /**
                     * Link text shown in the navigation.
                     */
                    displayText: string;
                    /**
                     * URL outside this website the link points to.
                     */
                    targetLink: string;
                    displayIcon?: IconName;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'ExternalLinkItem';
                  }
              )[];
              id?: string | null;
              blockName?: string | null;
              blockType: 'NestedDropdown';
            }
          | {
              id?: string | null;
              blockName?: string | null;
              blockType: 'VisualDivider';
            }
        )[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'NavDropdown';
      }
    | {
        /**
         * Link text shown in the navigation.
         */
        displayText: string;
        targetLink: StaticTargetLink;
        displayIcon?: IconName;
        id?: string | null;
        blockName?: string | null;
        blockType: 'LinkItem';
      }
    | {
        /**
         * Link text shown in the navigation.
         */
        displayText: string;
        /**
         * URL outside this website the link points to.
         */
        targetLink: string;
        displayIcon?: IconName;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ExternalLinkItem';
      }
    | {
        /**
         * Label of the menu listing the WCA's social media profiles.
         */
        label: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'SocialsMenu';
      }
  )[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * Links in the main part of the footer.
   */
  navigationLinks?:
    | (
        | {
            /**
             * Link text shown in the footer.
             */
            displayText: string;
            targetLink: StaticTargetLink;
            id?: string | null;
            blockName?: string | null;
            blockType: 'FooterLinkItem';
          }
        | {
            /**
             * Link text shown in the footer.
             */
            displayText: string;
            /**
             * URL outside this website the link points to.
             */
            targetLink: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'FooterExternalLinkItem';
          }
      )[]
    | null;
  /**
   * Links in the legal row at the very bottom of the footer.
   */
  legalLinks?:
    | {
        /**
         * Link text shown in the footer.
         */
        displayText: string;
        targetLink: StaticTargetLink;
        id?: string | null;
        blockName?: string | null;
        blockType: 'FooterLinkItem';
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links".
 */
export interface SocialLink {
  id: string;
  /**
   * The WCA's social media profiles, shown in the footer and in the navigation's socials menu.
   */
  links?:
    | {
        /**
         * Name of the social network, shown next to its icon and read out by screen readers.
         */
        displayText: string;
        /**
         * URL of the WCA's profile on that network.
         */
        targetLink: string;
        /**
         * Icon shown for this network.
         */
        displayIcon:
          | 'About the Regulations'
          | 'About the WCA'
          | 'Admin Results'
          | 'All Competitions'
          | 'Bookmark'
          | 'Clone'
          | 'Competition Not Started'
          | 'Registration Closed'
          | 'Registration Closed (Red)'
          | 'Registration Full but Open'
          | 'Registration Full but Open (Orange)'
          | 'Registration Not Full, Open'
          | 'Registration Not Full, Open (Green)'
          | 'Registration Not Open Yet'
          | 'Registration Not Open Yet (Grey)'
          | 'Registration Open Date'
          | 'Registration Close Date'
          | 'Competitors'
          | 'Contact'
          | 'Delegate Report'
          | 'Details'
          | 'Developer Export'
          | 'Disciplinary Log'
          | 'Disclaimer'
          | 'Download'
          | 'Edit'
          | 'Educational Resources'
          | 'Error'
          | 'External Link'
          | 'Facebook'
          | 'Filters'
          | 'GitHub'
          | 'Guidelines'
          | 'Help and FAQs'
          | 'Incidents Log'
          | 'Information'
          | 'Instagram'
          | 'Language'
          | 'List'
          | 'Location'
          | 'Manage Tabs'
          | 'Map'
          | 'Media Submission'
          | 'Menu'
          | 'Multimedia'
          | 'My Competitions'
          | 'My Results'
          | 'National Championship'
          | 'New Competition'
          | 'On-the-Spot Registration'
          | 'Payment'
          | 'Privacy'
          | 'Rankings'
          | 'Records'
          | 'Regional Organisations'
          | 'Register'
          | 'Registration'
          | 'Regulations and Guidelines'
          | 'Regulations History'
          | 'Regulations'
          | 'Results Export'
          | 'Scrambles'
          | 'Search'
          | 'Spectators'
          | 'Speedcubing History'
          | 'Spots Left'
          | 'Statistics'
          | 'Teams, Committees and Councils'
          | 'Tools'
          | 'Translators'
          | 'Twitch'
          | 'User'
          | 'Users / Persons'
          | 'Venue'
          | 'WCA Delegates'
          | 'WCA Documents'
          | 'WCA Live'
          | 'WCA Logo'
          | 'WCA Officers and Board'
          | 'Weibo'
          | 'X (formerly Twitter)'
          | 'YouTube'
          | '222Icon'
          | '333bfIcon'
          | '333fmIcon'
          | '333ftIcon'
          | '333Icon'
          | '333mbfIcon'
          | '333ohIcon'
          | '333mboIcon'
          | '444bfIcon'
          | '444Icon'
          | '555bfIcon'
          | '555Icon'
          | '666Icon'
          | '777Icon'
          | 'ClockIcon'
          | 'FtoIcon'
          | 'MagicIcon'
          | 'MinxIcon'
          | 'MmagicIcon'
          | 'PyramIcon'
          | 'SkewbIcon'
          | 'Sq1Icon';
        id?: string | null;
        blockName?: string | null;
        blockType: 'SocialLinkItem';
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  /**
   * The boxes making up the home page, top to bottom.
   */
  layout: (
    | TextCardBlock
    | AnnouncementsSectionBlock
    | ImageBannerBlock
    | ImageOnlyCardBlock
    | TestimonialsBlock
    | FeaturedCompetitionsBlock
    | TwoBlocksLevel2Block
  )[];
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextCardBlock".
 */
export interface TextCardBlock {
  /**
   * Heading shown at the top of the card.
   */
  heading: string;
  /**
   * Body text of the card, shown under the heading.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  bodyMarkdown?: string | null;
  /**
   * Draw a horizontal line between the heading and the body
   */
  separatorAfterHeading: boolean;
  /**
   * Optional call-to-action button shown below the body.
   */
  buttons?: BentoActionButton[] | null;
  /**
   * Optional image shown above the heading.
   */
  headerImage?: (string | null) | Media;
  colorPalette: ColorPaletteSelect;
  id?: string | null;
  blockName?: string | null;
  blockType: 'TextCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BentoActionButton".
 */
export interface BentoActionButton {
  /**
   * Label written on the button.
   */
  displayText: string;
  /**
   * URL the button links to.
   */
  hyperlink: string;
  /**
   * Open this link in a new tab
   */
  newTab?: boolean | null;
  /**
   * Buttons are solid blue by default. If you click this checkbox, their color will follow the original text box instead
   */
  inheritColorScheme: boolean;
  id?: string | null;
  blockName?: string | null;
  blockType: 'actionButton';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AnnouncementsSectionBlock".
 */
export interface AnnouncementsSectionBlock {
  /**
   * Announcement shown large at the top of the section.
   */
  mainAnnouncement: string | Announcement;
  /**
   * Announcements listed under the main one.
   */
  furtherAnnouncements?: (string | Announcement)[] | null;
  /**
   * Show a link to the full list of announcements at the bottom of the section
   */
  showSeeAll: boolean;
  colorPalette: ColorPaletteSelect;
  id?: string | null;
  blockName?: string | null;
  blockType: 'AnnouncementsSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBannerBlock".
 */
export interface ImageBannerBlock {
  /**
   * Heading shown next to the banner image.
   */
  heading?: string | null;
  /**
   * Body text shown under the heading.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  bodyMarkdown?: string | null;
  /**
   * The image shown beside the text.
   */
  mainImage: string | Media;
  /**
   * Which side of the text the image sits on
   */
  imagePosition: 'left' | 'right';
  colorPalette: ColorPaletteSelect;
  /**
   * Use a slightly darker nuance of the color palette
   */
  colorPaletteDarker?: boolean | null;
  headingColor?: ColorPaletteSelect;
  /**
   * Optional decorative image drawn behind the banner's content.
   */
  bgImage?: (string | null) | Media;
  /**
   * The size of the background image in percent (%)
   */
  bgSize: number;
  /**
   * Which side of the banner the background image sits on
   */
  bgPos: 'right' | 'left';
  id?: string | null;
  blockName?: string | null;
  blockType: 'ImageBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageOnlyCardBlock".
 */
export interface ImageOnlyCardBlock {
  /**
   * The image filling the card.
   */
  mainImage: string | Media;
  /**
   * Optional caption shown over the image.
   */
  heading?: string | null;
  /**
   * Optional. If set, the whole card becomes a link to this URL.
   */
  url?: string | null;
  /**
   * Open this link in a new tab
   */
  newTab?: boolean | null;
  /**
   * Whether the caption sits above or below the image
   */
  textPosition?: ('top' | 'bottom') | null;
  colorPalette: ColorPaletteSelect;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ImageOnlyCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  /**
   * The testimonials the spinner rotates through.
   */
  slides: {
    /**
     * The testimonial shown on this slide.
     */
    testimonial: string | Testimonial;
    colorPalette: ColorPaletteSelect;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'TestimonialsSpinner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCompetitionsBlock".
 */
export interface FeaturedCompetitionsBlock {
  /**
   * The competitions to feature, in the order they appear.
   */
  competitions?:
    | {
        /**
         * WCA competition ID, for example 'WC2025'.
         */
        competitionId: string;
        colorPalette: ColorPaletteSelect;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'FeaturedComps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoBlocksLevel2Block".
 */
export interface TwoBlocksLevel2Block {
  /**
   * How the available width is split between the left and right column.
   */
  ratio: '1/3 & 2/3' | '2/3 & 1/3' | '1/2 & 1/2' | '1/4 & 3/4' | '3/4 & 1/4';
  /**
   * Boxes stacked in the left column.
   */
  left: (
    | TextCardBlock
    | AnnouncementsSectionBlock
    | ImageBannerBlock
    | ImageOnlyCardBlock
    | TestimonialsBlock
    | FeaturedCompetitionsBlock
    | TwoBlocksLevel1Block
  )[];
  /**
   * Boxes stacked in the right column.
   */
  right: (
    | TextCardBlock
    | AnnouncementsSectionBlock
    | ImageBannerBlock
    | ImageOnlyCardBlock
    | TestimonialsBlock
    | FeaturedCompetitionsBlock
    | TwoBlocksLevel1Block
  )[];
  growthStrategy?: GrowthStrategy;
  id?: string | null;
  blockName?: string | null;
  blockType: 'twoBlocksLevel2';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoBlocksLevel1Block".
 */
export interface TwoBlocksLevel1Block {
  /**
   * How the available width is split between the left and right column.
   */
  ratio: '1/3 & 2/3' | '2/3 & 1/3' | '1/2 & 1/2' | '1/4 & 3/4' | '3/4 & 1/4';
  /**
   * Boxes stacked in the left column.
   */
  left: (
    | TextCardBlock
    | AnnouncementsSectionBlock
    | ImageBannerBlock
    | ImageOnlyCardBlock
    | TestimonialsBlock
    | FeaturedCompetitionsBlock
    | TwoBlocksLevel0Block
  )[];
  /**
   * Boxes stacked in the right column.
   */
  right: (
    | TextCardBlock
    | AnnouncementsSectionBlock
    | ImageBannerBlock
    | ImageOnlyCardBlock
    | TestimonialsBlock
    | FeaturedCompetitionsBlock
    | TwoBlocksLevel0Block
  )[];
  growthStrategy?: GrowthStrategy;
  id?: string | null;
  blockName?: string | null;
  blockType: 'twoBlocksLevel1';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoBlocksLevel0Block".
 */
export interface TwoBlocksLevel0Block {
  /**
   * How the available width is split between the left and right column.
   */
  ratio: '1/3 & 2/3' | '2/3 & 1/3' | '1/2 & 1/2' | '1/4 & 3/4' | '3/4 & 1/4';
  /**
   * Boxes stacked in the left column.
   */
  left: (
    | TextCardBlock
    | AnnouncementsSectionBlock
    | ImageBannerBlock
    | ImageOnlyCardBlock
    | TestimonialsBlock
    | FeaturedCompetitionsBlock
  )[];
  /**
   * Boxes stacked in the right column.
   */
  right: (
    | TextCardBlock
    | AnnouncementsSectionBlock
    | ImageBannerBlock
    | ImageOnlyCardBlock
    | TestimonialsBlock
    | FeaturedCompetitionsBlock
  )[];
  growthStrategy?: GrowthStrategy;
  id?: string | null;
  blockName?: string | null;
  blockType: 'twoBlocksLevel0';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-page".
 */
export interface AboutUsPage {
  id: string;
  /**
   * The sections making up the About Us page, top to bottom.
   */
  blocks: (
    | {
        /**
         * Text shown above the buttons.
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        contentMarkdown?: string | null;
        /**
         * The buttons offered under the text.
         */
        buttons: {
          /**
           * Label written on the button.
           */
          label: string;
          /**
           * URL the button links to.
           */
          url: string;
          /**
           * Open this link in a new tab
           */
          newTab?: boolean | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'callToAction';
      }
    | {
        /**
         * Heading of this section of the About Us page.
         */
        title: string;
        /**
         * Optional image shown alongside the text.
         */
        image?: (string | null) | Media;
        /**
         * Body text of this section.
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        contentMarkdown?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'simpleItem';
      }
    | {
        /**
         * The quoted words themselves.
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        contentMarkdown?: string | null;
        /**
         * Name of the person the quote is attributed to.
         */
        quotedPerson: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'quote';
      }
  )[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-page".
 */
export interface PrivacyPage {
  id: string;
  /**
   * Text shown at the top of the Privacy page, above the numbered paragraphs.
   */
  preamble: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  preambleMarkdown?: string | null;
  /**
   * The paragraphs making up the Privacy page, top to bottom.
   */
  blocks: {
    /**
     * Heading shown above the paragraph.
     */
    title: string;
    /**
     * Body text of the paragraph.
     */
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    contentMarkdown?: string | null;
    id?: string | null;
    blockName?: string | null;
    blockType: 'paragraph';
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disclaimer-page".
 */
export interface DisclaimerPage {
  id: string;
  /**
   * The paragraphs making up the Disclaimer page, top to bottom.
   */
  blocks: {
    /**
     * Heading shown above the paragraph.
     */
    title: string;
    /**
     * Body text of the paragraph.
     */
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    contentMarkdown?: string | null;
    id?: string | null;
    blockName?: string | null;
    blockType: 'paragraph';
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speedcubing-history-page".
 */
export interface SpeedcubingHistoryPage {
  id: string;
  /**
   * The sections making up the Speedcubing History page, top to bottom.
   */
  blocks: (
    | {
        /**
         * Heading shown above the paragraph.
         */
        title: string;
        /**
         * Body text of the paragraph.
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        contentMarkdown?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'paragraph';
      }
    | {
        /**
         * Caption shown underneath the image.
         */
        caption: string;
        /**
         * The image to show.
         */
        image: string | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'captionedImage';
      }
    | {
        /**
         * The quoted words themselves.
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        contentMarkdown?: string | null;
        /**
         * Name of the person the quote is attributed to.
         */
        quotedPerson: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'quote';
      }
  )[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-regulations-page".
 */
export interface AboutRegulationsPage {
  id: string;
  /**
   * The paragraphs making up the About Regulations page, top to bottom.
   */
  blocks: {
    /**
     * Heading shown above the paragraph.
     */
    title: string;
    /**
     * Body text of the paragraph.
     */
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    contentMarkdown?: string | null;
    id?: string | null;
    blockName?: string | null;
    blockType: 'paragraph';
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents-page".
 */
export interface DocumentsPage {
  id: string;
  /**
   * The documents listed on the Documents page, in the order they appear.
   */
  documents: {
    /**
     * The document to list here.
     */
    document: string | Document;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page".
 */
export interface FaqPage {
  id: string;
  /**
   * Text shown above the list of questions on the FAQ page.
   */
  introText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  introTextMarkdown?: string | null;
  /**
   * The questions listed on the FAQ page, in the order they appear.
   */
  questions: {
    /**
     * The question to list here.
     */
    faqQuestion: string | FaqQuestion;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logo-page".
 */
export interface LogoPage {
  id: string;
  /**
   * The sections making up the Logo page, top to bottom.
   */
  blocks: (
    | {
        /**
         * Optional heading shown above the paragraph.
         */
        title?: string | null;
        /**
         * Body text of the paragraph.
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        contentMarkdown?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'paragraph';
      }
    | {
        /**
         * Name of this logo variant.
         */
        title: string;
        /**
         * Explains when this logo variant should be used.
         */
        caption: string;
        /**
         * Tick this for variants without wordmark, so they are rendered smaller.
         */
        logoOnly?: boolean | null;
        /**
         * The files this variant is offered in.
         */
        images: {
          /**
           * The logo file to show.
           */
          image: string | Media;
          /**
           * Tick this when the logo needs a dark backdrop to be visible.
           */
          darkBackground?: boolean | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'logoVariant';
      }
    | {
        /**
         * URL of the logo package the download button points to.
         */
        url: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'logoDownload';
      }
  )[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav_select".
 */
export interface NavSelect<T extends boolean = true> {
  entry?:
    | T
    | {
        NavDropdown?:
          | T
          | {
              title?: T;
              displayIcon?: T;
              entries?:
                | T
                | {
                    LinkItem?:
                      | T
                      | {
                          displayText?: T;
                          targetLink?: T;
                          displayIcon?: T;
                          id?: T;
                          blockName?: T;
                        };
                    ExternalLinkItem?:
                      | T
                      | {
                          displayText?: T;
                          targetLink?: T;
                          displayIcon?: T;
                          id?: T;
                          blockName?: T;
                        };
                    NestedDropdown?:
                      | T
                      | {
                          title?: T;
                          displayIcon?: T;
                          entries?:
                            | T
                            | {
                                LinkItem?:
                                  | T
                                  | {
                                      displayText?: T;
                                      targetLink?: T;
                                      displayIcon?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                ExternalLinkItem?:
                                  | T
                                  | {
                                      displayText?: T;
                                      targetLink?: T;
                                      displayIcon?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                              };
                          id?: T;
                          blockName?: T;
                        };
                    VisualDivider?:
                      | T
                      | {
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        LinkItem?:
          | T
          | {
              displayText?: T;
              targetLink?: T;
              displayIcon?: T;
              id?: T;
              blockName?: T;
            };
        ExternalLinkItem?:
          | T
          | {
              displayText?: T;
              targetLink?: T;
              displayIcon?: T;
              id?: T;
              blockName?: T;
            };
        SocialsMenu?:
          | T
          | {
              label?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navigationLinks?:
    | T
    | {
        FooterLinkItem?:
          | T
          | {
              displayText?: T;
              targetLink?: T;
              id?: T;
              blockName?: T;
            };
        FooterExternalLinkItem?:
          | T
          | {
              displayText?: T;
              targetLink?: T;
              id?: T;
              blockName?: T;
            };
      };
  legalLinks?:
    | T
    | {
        FooterLinkItem?:
          | T
          | {
              displayText?: T;
              targetLink?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links_select".
 */
export interface SocialLinksSelect<T extends boolean = true> {
  links?:
    | T
    | {
        SocialLinkItem?:
          | T
          | {
              displayText?: T;
              targetLink?: T;
              displayIcon?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        TextCard?: T | TextCardBlockSelect<T>;
        AnnouncementsSection?: T | AnnouncementsSectionBlockSelect<T>;
        ImageBanner?: T | ImageBannerBlockSelect<T>;
        ImageOnlyCard?: T | ImageOnlyCardBlockSelect<T>;
        TestimonialsSpinner?: T | TestimonialsBlockSelect<T>;
        FeaturedComps?: T | FeaturedCompetitionsBlockSelect<T>;
        twoBlocksLevel2?: T | TwoBlocksLevel2BlockSelect<T>;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextCardBlock_select".
 */
export interface TextCardBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  bodyMarkdown?: T;
  separatorAfterHeading?: T;
  buttons?:
    | T
    | {
        actionButton?: T | BentoActionButtonSelect<T>;
      };
  headerImage?: T;
  colorPalette?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BentoActionButton_select".
 */
export interface BentoActionButtonSelect<T extends boolean = true> {
  displayText?: T;
  hyperlink?: T;
  newTab?: T;
  inheritColorScheme?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AnnouncementsSectionBlock_select".
 */
export interface AnnouncementsSectionBlockSelect<T extends boolean = true> {
  mainAnnouncement?: T;
  furtherAnnouncements?: T;
  showSeeAll?: T;
  colorPalette?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBannerBlock_select".
 */
export interface ImageBannerBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  bodyMarkdown?: T;
  mainImage?: T;
  imagePosition?: T;
  colorPalette?: T;
  colorPaletteDarker?: T;
  headingColor?: T;
  bgImage?: T;
  bgSize?: T;
  bgPos?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageOnlyCardBlock_select".
 */
export interface ImageOnlyCardBlockSelect<T extends boolean = true> {
  mainImage?: T;
  heading?: T;
  url?: T;
  newTab?: T;
  textPosition?: T;
  colorPalette?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  slides?:
    | T
    | {
        testimonial?: T;
        colorPalette?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCompetitionsBlock_select".
 */
export interface FeaturedCompetitionsBlockSelect<T extends boolean = true> {
  competitions?:
    | T
    | {
        competitionId?: T;
        colorPalette?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoBlocksLevel2Block_select".
 */
export interface TwoBlocksLevel2BlockSelect<T extends boolean = true> {
  ratio?: T;
  left?:
    | T
    | {
        TextCard?: T | TextCardBlockSelect<T>;
        AnnouncementsSection?: T | AnnouncementsSectionBlockSelect<T>;
        ImageBanner?: T | ImageBannerBlockSelect<T>;
        ImageOnlyCard?: T | ImageOnlyCardBlockSelect<T>;
        TestimonialsSpinner?: T | TestimonialsBlockSelect<T>;
        FeaturedComps?: T | FeaturedCompetitionsBlockSelect<T>;
        twoBlocksLevel1?: T | TwoBlocksLevel1BlockSelect<T>;
      };
  right?:
    | T
    | {
        TextCard?: T | TextCardBlockSelect<T>;
        AnnouncementsSection?: T | AnnouncementsSectionBlockSelect<T>;
        ImageBanner?: T | ImageBannerBlockSelect<T>;
        ImageOnlyCard?: T | ImageOnlyCardBlockSelect<T>;
        TestimonialsSpinner?: T | TestimonialsBlockSelect<T>;
        FeaturedComps?: T | FeaturedCompetitionsBlockSelect<T>;
        twoBlocksLevel1?: T | TwoBlocksLevel1BlockSelect<T>;
      };
  growthStrategy?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoBlocksLevel1Block_select".
 */
export interface TwoBlocksLevel1BlockSelect<T extends boolean = true> {
  ratio?: T;
  left?:
    | T
    | {
        TextCard?: T | TextCardBlockSelect<T>;
        AnnouncementsSection?: T | AnnouncementsSectionBlockSelect<T>;
        ImageBanner?: T | ImageBannerBlockSelect<T>;
        ImageOnlyCard?: T | ImageOnlyCardBlockSelect<T>;
        TestimonialsSpinner?: T | TestimonialsBlockSelect<T>;
        FeaturedComps?: T | FeaturedCompetitionsBlockSelect<T>;
        twoBlocksLevel0?: T | TwoBlocksLevel0BlockSelect<T>;
      };
  right?:
    | T
    | {
        TextCard?: T | TextCardBlockSelect<T>;
        AnnouncementsSection?: T | AnnouncementsSectionBlockSelect<T>;
        ImageBanner?: T | ImageBannerBlockSelect<T>;
        ImageOnlyCard?: T | ImageOnlyCardBlockSelect<T>;
        TestimonialsSpinner?: T | TestimonialsBlockSelect<T>;
        FeaturedComps?: T | FeaturedCompetitionsBlockSelect<T>;
        twoBlocksLevel0?: T | TwoBlocksLevel0BlockSelect<T>;
      };
  growthStrategy?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoBlocksLevel0Block_select".
 */
export interface TwoBlocksLevel0BlockSelect<T extends boolean = true> {
  ratio?: T;
  left?:
    | T
    | {
        TextCard?: T | TextCardBlockSelect<T>;
        AnnouncementsSection?: T | AnnouncementsSectionBlockSelect<T>;
        ImageBanner?: T | ImageBannerBlockSelect<T>;
        ImageOnlyCard?: T | ImageOnlyCardBlockSelect<T>;
        TestimonialsSpinner?: T | TestimonialsBlockSelect<T>;
        FeaturedComps?: T | FeaturedCompetitionsBlockSelect<T>;
      };
  right?:
    | T
    | {
        TextCard?: T | TextCardBlockSelect<T>;
        AnnouncementsSection?: T | AnnouncementsSectionBlockSelect<T>;
        ImageBanner?: T | ImageBannerBlockSelect<T>;
        ImageOnlyCard?: T | ImageOnlyCardBlockSelect<T>;
        TestimonialsSpinner?: T | TestimonialsBlockSelect<T>;
        FeaturedComps?: T | FeaturedCompetitionsBlockSelect<T>;
      };
  growthStrategy?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-page_select".
 */
export interface AboutUsPageSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        callToAction?:
          | T
          | {
              content?: T;
              contentMarkdown?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        simpleItem?:
          | T
          | {
              title?: T;
              image?: T;
              content?: T;
              contentMarkdown?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              content?: T;
              contentMarkdown?: T;
              quotedPerson?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-page_select".
 */
export interface PrivacyPageSelect<T extends boolean = true> {
  preamble?: T;
  preambleMarkdown?: T;
  blocks?:
    | T
    | {
        paragraph?:
          | T
          | {
              title?: T;
              content?: T;
              contentMarkdown?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disclaimer-page_select".
 */
export interface DisclaimerPageSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        paragraph?:
          | T
          | {
              title?: T;
              content?: T;
              contentMarkdown?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speedcubing-history-page_select".
 */
export interface SpeedcubingHistoryPageSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        paragraph?:
          | T
          | {
              title?: T;
              content?: T;
              contentMarkdown?: T;
              id?: T;
              blockName?: T;
            };
        captionedImage?:
          | T
          | {
              caption?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              content?: T;
              contentMarkdown?: T;
              quotedPerson?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-regulations-page_select".
 */
export interface AboutRegulationsPageSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        paragraph?:
          | T
          | {
              title?: T;
              content?: T;
              contentMarkdown?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents-page_select".
 */
export interface DocumentsPageSelect<T extends boolean = true> {
  documents?:
    | T
    | {
        document?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page_select".
 */
export interface FaqPageSelect<T extends boolean = true> {
  introText?: T;
  introTextMarkdown?: T;
  questions?:
    | T
    | {
        faqQuestion?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logo-page_select".
 */
export interface LogoPageSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        paragraph?:
          | T
          | {
              title?: T;
              content?: T;
              contentMarkdown?: T;
              id?: T;
              blockName?: T;
            };
        logoVariant?:
          | T
          | {
              title?: T;
              caption?: T;
              logoOnly?: T;
              images?:
                | T
                | {
                    image?: T;
                    darkBackground?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logoDownload?:
          | T
          | {
              url?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}