/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ColorPaletteSelect".
 */
export type ColorPaletteSelect = 'blue' | 'red' | 'green' | 'orange' | 'yellow' | 'white';
/**
 * Icon name
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconName".
 */
export type IconName =
  | 'About the Regulations'
  | 'About the WCA'
  | 'Admin Results'
  | 'All Competitions'
  | 'Bookmark'
  | 'Clone'
  | 'Competition Not Started'
  | 'Registration Closed'
  | 'Registration Closed (Red)'
  | 'Registration Full but Open'
  | 'Registration Full but Open (Orange)'
  | 'Registration Not Full, Open'
  | 'Registration Not Full, Open (Green)'
  | 'Registration Not Open Yet'
  | 'Registration Not Open Yet (Grey)'
  | 'Registration Open Date'
  | 'Registration Close Date'
  | 'Competitors'
  | 'Contact'
  | 'Delegate Report'
  | 'Details'
  | 'Developer Export'
  | 'Disciplinary Log'
  | 'Disclaimer'
  | 'Download'
  | 'Edit'
  | 'Educational Resources'
  | 'Error'
  | 'External Link'
  | 'Facebook'
  | 'Filters'
  | 'GitHub'
  | 'Guidelines'
  | 'Help and FAQs'
  | 'Incidents Log'
  | 'Information'
  | 'Instagram'
  | 'Language'
  | 'List'
  | 'Location'
  | 'Manage Tabs'
  | 'Map'
  | 'Media Submission'
  | 'Menu'
  | 'Multimedia'
  | 'My Competitions'
  | 'My Results'
  | 'National Championship'
  | 'New Competition'
  | 'On-the-Spot Registration'
  | 'Payment'
  | 'Privacy'
  | 'Rankings'
  | 'Records'
  | 'Regional Organisations'
  | 'Register'
  | 'Registration'
  | 'Regulations and Guidelines'
  | 'Regulations History'
  | 'Regulations'
  | 'Results Export'
  | 'Scrambles'
  | 'Search'
  | 'Spectators'
  | 'Speedcubing History'
  | 'Spots Left'
  | 'Statistics'
  | 'Teams, Committees and Councils'
  | 'Tools'
  | 'Translators'
  | 'Twitch'
  | 'User'
  | 'Users / Persons'
  | 'Venue'
  | 'WCA Delegates'
  | 'WCA Documents'
  | 'WCA Live'
  | 'WCA Officers and Board'
  | 'Weibo'
  | 'X (formerly Twitter)'
  | 'YouTube'
  | '222Icon'
  | '333bfIcon'
  | '333fmIcon'
  | '333ftIcon'
  | '333Icon'
  | '333mbfIcon'
  | '333ohIcon'
  | '333mboIcon'
  | '444bfIcon'
  | '444Icon'
  | '555bfIcon'
  | '555Icon'
  | '666Icon'
  | '777Icon'
  | 'ClockIcon'
  | 'MagicIcon'
  | 'MinxIcon'
  | 'MmagicIcon'
  | 'PyramIcon'
  | 'SkewbIcon'
  | 'Sq1Icon';
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StaticTargetLink".
 */
export type StaticTargetLink =
  | '/'
  | '/about'
  | '/competitions'
  | '/delegates'
  | '/disclaimer'
  | '/documents'
  | '/export/developer'
  | '/export/results'
  | '/faq'
  | '/incidents'
  | '/logo'
  | '/officers-and-board'
  | '/organizations'
  | '/privacy'
  | '/regulations/about'
  | '/regulations/history'
  | '/regulations/scrambles'
  | '/regulations/translations'
  | '/results/rankings'
  | '/results/records'
  | '/score-tools'
  | '/speedcubing-history'
  | '/teams-committees'
  | '/translators';
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    testimonials: Testimonial;
    announcements: Announcement;
    faqCategories: FaqCategory;
    faqQuestions: FaqQuestion;
    users: User;
    documents: Document;
    regulationsHistoryItem: RegulationsHistoryItem;
    tools: Tool;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    faqCategories: {
      relatedQuestions: 'faqQuestions';
    };
  };
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    faqCategories: FaqCategoriesSelect<false> | FaqCategoriesSelect<true>;
    faqQuestions: FaqQuestionsSelect<false> | FaqQuestionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    regulationsHistoryItem: RegulationsHistoryItemSelect<false> | RegulationsHistoryItemSelect<true>;
    tools: ToolsSelect<false> | ToolsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    nav: Nav;
    home: Home;
    'about-us-page': AboutUsPage;
    'privacy-page': PrivacyPage;
    'disclaimer-page': DisclaimerPage;
    'speedcubing-history-page': SpeedcubingHistoryPage;
    'about-regulations-page': AboutRegulationsPage;
    'documents-page': DocumentsPage;
    'faq-page': FaqPage;
    'logo-page': LogoPage;
  };
  globalsSelect: {
    nav: NavSelect<false> | NavSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    'about-us-page': AboutUsPageSelect<false> | AboutUsPageSelect<true>;
    'privacy-page': PrivacyPageSelect<false> | PrivacyPageSelect<true>;
    'disclaimer-page': DisclaimerPageSelect<false> | DisclaimerPageSelect<true>;
    'speedcubing-history-page': SpeedcubingHistoryPageSelect<false> | SpeedcubingHistoryPageSelect<true>;
    'about-regulations-page': AboutRegulationsPageSelect<false> | AboutRegulationsPageSelect<true>;
    'documents-page': DocumentsPageSelect<false> | DocumentsPageSelect<true>;
    'faq-page': FaqPageSelect<false> | FaqPageSelect<true>;
    'logo-page': LogoPageSelect<false> | LogoPageSelect<true>;
  };
  locale:
    | 'en'
    | 'ca'
    | 'cs'
    | 'da'
    | 'de'
    | 'eo'
    | 'es-ES'
    | 'es-419'
    | 'eu'
    | 'fi'
    | 'fr'
    | 'fr-CA'
    | 'hr'
    | 'hu'
    | 'id'
    | 'it'
    | 'ja'
    | 'kk'
    | 'ko'
    | 'nl'
    | 'pl'
    | 'pt'
    | 'pt-BR'
    | 'ro'
    | 'ru'
    | 'sk'
    | 'sl'
    | 'sv'
    | 'th'
    | 'uk'
    | 'vi'
    | 'zh-CN'
    | 'zh-TW';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  customLink?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  image?: (string | null) | Media;
  punchline: string;
  fullTestimonial: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  fullTestimonialMarkdown?: string | null;
  whoDunnit: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: string;
  image?: (string | null) | Media;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  contentMarkdown?: string | null;
  publishedAt: string;
  publishedBy: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  email: string;
  emailVerified?: string | null;
  name?: string | null;
  image?: string | null;
  roles?: string[];
  accounts?:
    | {
        provider: string;
        providerAccountId: string;
        type: 'oidc' | 'oauth' | 'email' | 'webauthn';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqCategories".
 */
export interface FaqCategory {
  id: string;
  title: string;
  colorPalette: ColorPaletteSelect;
  relatedQuestions?: {
    docs?: (string | FaqQuestion)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqQuestions".
 */
export interface FaqQuestion {
  id: string;
  category: string | FaqCategory;
  question: string;
  answer: string;
  answerRichtext?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  answerRichtextMarkdown?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: string;
  title: string;
  icon: IconName;
  link: string;
  /**
   * Category name (used for grouping documents)
   */
  category?: ('motions' | 'minutes' | 'policies' | 'finances') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulationsHistoryItem".
 */
export interface RegulationsHistoryItem {
  id: string;
  version: string;
  url: string;
  changesUrl?: string | null;
  summarizedChangesUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools".
 */
export interface Tool {
  id: string;
  name: string;
  description: string;
  homepageLink: string;
  guideLink?: string | null;
  sourceCodeLink?: string | null;
  isOfficial?: boolean | null;
  author: string;
  category: 'before' | 'during' | 'after';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'announcements';
        value: string | Announcement;
      } | null)
    | ({
        relationTo: 'faqCategories';
        value: string | FaqCategory;
      } | null)
    | ({
        relationTo: 'faqQuestions';
        value: string | FaqQuestion;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'documents';
        value: string | Document;
      } | null)
    | ({
        relationTo: 'regulationsHistoryItem';
        value: string | RegulationsHistoryItem;
      } | null)
    | ({
        relationTo: 'tools';
        value: string | Tool;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  customLink?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  image?: T;
  punchline?: T;
  fullTestimonial?: T;
  fullTestimonialMarkdown?: T;
  whoDunnit?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  image?: T;
  title?: T;
  content?: T;
  contentMarkdown?: T;
  publishedAt?: T;
  publishedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqCategories_select".
 */
export interface FaqCategoriesSelect<T extends boolean = true> {
  title?: T;
  colorPalette?: T;
  relatedQuestions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqQuestions_select".
 */
export interface FaqQuestionsSelect<T extends boolean = true> {
  category?: T;
  question?: T;
  answer?: T;
  answerRichtext?: T;
  answerRichtextMarkdown?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  id?: T;
  email?: T;
  emailVerified?: T;
  name?: T;
  image?: T;
  roles?: T;
  accounts?:
    | T
    | {
        provider?: T;
        providerAccountId?: T;
        type?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  icon?: T;
  link?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulationsHistoryItem_select".
 */
export interface RegulationsHistoryItemSelect<T extends boolean = true> {
  version?: T;
  url?: T;
  changesUrl?: T;
  summarizedChangesUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools_select".
 */
export interface ToolsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  homepageLink?: T;
  guideLink?: T;
  sourceCodeLink?: T;
  isOfficial?: T;
  author?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav".
 */
export interface Nav {
  id: string;
  entry: (
    | {
        title: string;
        displayIcon?: IconName;
        entries: (
          | {
              displayText: string;
              targetLink: StaticTargetLink;
              displayIcon?: IconName;
              id?: string | null;
              blockName?: string | null;
              blockType: 'LinkItem';
            }
          | {
              displayText: string;
              targetLink: string;
              displayIcon?: IconName;
              id?: string | null;
              blockName?: string | null;
              blockType: 'ExternalLinkItem';
            }
          | {
              title: string;
              displayIcon?: IconName;
              entries: (
                | {
                    displayText: string;
                    targetLink: StaticTargetLink;
                    displayIcon?: IconName;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'LinkItem';
                  }
                | {
                    displayText: string;
                    targetLink: string;
                    displayIcon?: IconName;
                    id?: string | null;
                    blockName?: string | null;
                    blockType: 'ExternalLinkItem';
                  }
              )[];
              id?: string | null;
              blockName?: string | null;
              blockType: 'NestedDropdown';
            }
          | {
              id?: string | null;
              blockName?: string | null;
              blockType: 'VisualDivider';
            }
        )[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'NavDropdown';
      }
    | {
        displayText: string;
        targetLink: StaticTargetLink;
        displayIcon?: IconName;
        id?: string | null;
        blockName?: string | null;
        blockType: 'LinkItem';
      }
    | {
        displayText: string;
        targetLink: string;
        displayIcon?: IconName;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ExternalLinkItem';
      }
  )[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  item: (TwoBlocksBlock | FullWidthBlock)[];
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoBlocksBlock".
 */
export interface TwoBlocksBlock {
  type: '1/3 & 2/3' | '2/3 & 1/3' | '1/2 & 1/2' | '1/4 & 3/4' | '3/4 & 1/4';
  alignment: 'horizontal' | 'vertical';
  blocks: (
    | TextCardBlock
    | AnnouncementsSectionBlock
    | ImageBannerBlock
    | ImageOnlyCardBlock
    | TestimonialsBlock
    | FeaturedCompetitionsBlock
    | TwoBlocksBranchBlock
  )[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'twoBlocks';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextCardBlock".
 */
export interface TextCardBlock {
  heading: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  bodyMarkdown?: string | null;
  separatorAfterHeading: boolean;
  buttonText?: string | null;
  buttonLink?: string | null;
  headerImage?: (string | null) | Media;
  colorPalette: ColorPaletteSelect;
  id?: string | null;
  blockName?: string | null;
  blockType: 'TextCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AnnouncementsSectionBlock".
 */
export interface AnnouncementsSectionBlock {
  mainAnnouncement: string | Announcement;
  furtherAnnouncements?: (string | Announcement)[] | null;
  colorPalette: ColorPaletteSelect;
  id?: string | null;
  blockName?: string | null;
  blockType: 'AnnouncementsSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBannerBlock".
 */
export interface ImageBannerBlock {
  heading: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  bodyMarkdown?: string | null;
  mainImage: string | Media;
  colorPalette: ColorPaletteSelect;
  /**
   * Use a slightly darker nuance of the color palette
   */
  colorPaletteDarker?: boolean | null;
  headingColor?: ColorPaletteSelect;
  bgImage?: (string | null) | Media;
  /**
   * The size of the background image in percent (%)
   */
  bgSize: number;
  bgPos: 'right' | 'left';
  id?: string | null;
  blockName?: string | null;
  blockType: 'ImageBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageOnlyCardBlock".
 */
export interface ImageOnlyCardBlock {
  mainImage: string | Media;
  heading?: string | null;
  colorPalette: ColorPaletteSelect;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ImageOnlyCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  slides: {
    testimonial: string | Testimonial;
    colorPalette: ColorPaletteSelect;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'TestimonialsSpinner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCompetitionsBlock".
 */
export interface FeaturedCompetitionsBlock {
  competitions?:
    | {
        competitionId: string;
        colorPalette: ColorPaletteSelect;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'FeaturedComps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoBlocksBranchBlock".
 */
export interface TwoBlocksBranchBlock {
  type: '1/3 & 2/3' | '2/3 & 1/3' | '1/2 & 1/2' | '1/4 & 3/4' | '3/4 & 1/4';
  alignment: 'horizontal' | 'vertical';
  blocks: (
    | TextCardBlock
    | AnnouncementsSectionBlock
    | ImageBannerBlock
    | ImageOnlyCardBlock
    | TestimonialsBlock
    | FeaturedCompetitionsBlock
    | TwoBlocksLeafBlock
  )[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'twoBlocksBranch';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoBlocksLeafBlock".
 */
export interface TwoBlocksLeafBlock {
  type: '1/3 & 2/3' | '2/3 & 1/3' | '1/2 & 1/2' | '1/4 & 3/4' | '3/4 & 1/4';
  alignment: 'horizontal' | 'vertical';
  blocks: (
    | TextCardBlock
    | AnnouncementsSectionBlock
    | ImageBannerBlock
    | ImageOnlyCardBlock
    | TestimonialsBlock
    | FeaturedCompetitionsBlock
  )[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'twoBlocksLeaf';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FullWidthBlock".
 */
export interface FullWidthBlock {
  blocks: (
    | TextCardBlock
    | AnnouncementsSectionBlock
    | ImageBannerBlock
    | ImageOnlyCardBlock
    | TestimonialsBlock
    | FeaturedCompetitionsBlock
  )[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'fullWidth';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-page".
 */
export interface AboutUsPage {
  id: string;
  blocks: (
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        contentMarkdown?: string | null;
        buttons: {
          label: string;
          url: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'callToAction';
      }
    | {
        title: string;
        image?: (string | null) | Media;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        contentMarkdown?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'simpleItem';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        contentMarkdown?: string | null;
        quotedPerson: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'quote';
      }
  )[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-page".
 */
export interface PrivacyPage {
  id: string;
  preamble: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  preambleMarkdown?: string | null;
  blocks: {
    title: string;
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    contentMarkdown?: string | null;
    id?: string | null;
    blockName?: string | null;
    blockType: 'paragraph';
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disclaimer-page".
 */
export interface DisclaimerPage {
  id: string;
  blocks: {
    title: string;
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    contentMarkdown?: string | null;
    id?: string | null;
    blockName?: string | null;
    blockType: 'paragraph';
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speedcubing-history-page".
 */
export interface SpeedcubingHistoryPage {
  id: string;
  blocks: (
    | {
        title: string;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        contentMarkdown?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'paragraph';
      }
    | {
        caption: string;
        image: string | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'captionedImage';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        contentMarkdown?: string | null;
        quotedPerson: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'quote';
      }
  )[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-regulations-page".
 */
export interface AboutRegulationsPage {
  id: string;
  blocks: {
    title: string;
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    contentMarkdown?: string | null;
    id?: string | null;
    blockName?: string | null;
    blockType: 'paragraph';
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents-page".
 */
export interface DocumentsPage {
  id: string;
  documents: {
    document: string | Document;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page".
 */
export interface FaqPage {
  id: string;
  introText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  introTextMarkdown?: string | null;
  questions: {
    faqQuestion: string | FaqQuestion;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logo-page".
 */
export interface LogoPage {
  id: string;
  blocks: (
    | {
        title: string;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        contentMarkdown?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'paragraph';
      }
    | {
        title: string;
        caption: string;
        images: {
          image: string | Media;
          darkBackground?: boolean | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'logoVariant';
      }
    | {
        url: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'logoDownload';
      }
  )[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav_select".
 */
export interface NavSelect<T extends boolean = true> {
  entry?:
    | T
    | {
        NavDropdown?:
          | T
          | {
              title?: T;
              displayIcon?: T;
              entries?:
                | T
                | {
                    LinkItem?:
                      | T
                      | {
                          displayText?: T;
                          targetLink?: T;
                          displayIcon?: T;
                          id?: T;
                          blockName?: T;
                        };
                    ExternalLinkItem?:
                      | T
                      | {
                          displayText?: T;
                          targetLink?: T;
                          displayIcon?: T;
                          id?: T;
                          blockName?: T;
                        };
                    NestedDropdown?:
                      | T
                      | {
                          title?: T;
                          displayIcon?: T;
                          entries?:
                            | T
                            | {
                                LinkItem?:
                                  | T
                                  | {
                                      displayText?: T;
                                      targetLink?: T;
                                      displayIcon?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                ExternalLinkItem?:
                                  | T
                                  | {
                                      displayText?: T;
                                      targetLink?: T;
                                      displayIcon?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                              };
                          id?: T;
                          blockName?: T;
                        };
                    VisualDivider?:
                      | T
                      | {
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        LinkItem?:
          | T
          | {
              displayText?: T;
              targetLink?: T;
              displayIcon?: T;
              id?: T;
              blockName?: T;
            };
        ExternalLinkItem?:
          | T
          | {
              displayText?: T;
              targetLink?: T;
              displayIcon?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  item?:
    | T
    | {
        twoBlocks?: T | TwoBlocksBlockSelect<T>;
        fullWidth?: T | FullWidthBlockSelect<T>;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoBlocksBlock_select".
 */
export interface TwoBlocksBlockSelect<T extends boolean = true> {
  type?: T;
  alignment?: T;
  blocks?:
    | T
    | {
        TextCard?: T | TextCardBlockSelect<T>;
        AnnouncementsSection?: T | AnnouncementsSectionBlockSelect<T>;
        ImageBanner?: T | ImageBannerBlockSelect<T>;
        ImageOnlyCard?: T | ImageOnlyCardBlockSelect<T>;
        TestimonialsSpinner?: T | TestimonialsBlockSelect<T>;
        FeaturedComps?: T | FeaturedCompetitionsBlockSelect<T>;
        twoBlocksBranch?: T | TwoBlocksBranchBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextCardBlock_select".
 */
export interface TextCardBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  bodyMarkdown?: T;
  separatorAfterHeading?: T;
  buttonText?: T;
  buttonLink?: T;
  headerImage?: T;
  colorPalette?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AnnouncementsSectionBlock_select".
 */
export interface AnnouncementsSectionBlockSelect<T extends boolean = true> {
  mainAnnouncement?: T;
  furtherAnnouncements?: T;
  colorPalette?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBannerBlock_select".
 */
export interface ImageBannerBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  bodyMarkdown?: T;
  mainImage?: T;
  colorPalette?: T;
  colorPaletteDarker?: T;
  headingColor?: T;
  bgImage?: T;
  bgSize?: T;
  bgPos?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageOnlyCardBlock_select".
 */
export interface ImageOnlyCardBlockSelect<T extends boolean = true> {
  mainImage?: T;
  heading?: T;
  colorPalette?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  slides?:
    | T
    | {
        testimonial?: T;
        colorPalette?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCompetitionsBlock_select".
 */
export interface FeaturedCompetitionsBlockSelect<T extends boolean = true> {
  competitions?:
    | T
    | {
        competitionId?: T;
        colorPalette?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoBlocksBranchBlock_select".
 */
export interface TwoBlocksBranchBlockSelect<T extends boolean = true> {
  type?: T;
  alignment?: T;
  blocks?:
    | T
    | {
        TextCard?: T | TextCardBlockSelect<T>;
        AnnouncementsSection?: T | AnnouncementsSectionBlockSelect<T>;
        ImageBanner?: T | ImageBannerBlockSelect<T>;
        ImageOnlyCard?: T | ImageOnlyCardBlockSelect<T>;
        TestimonialsSpinner?: T | TestimonialsBlockSelect<T>;
        FeaturedComps?: T | FeaturedCompetitionsBlockSelect<T>;
        twoBlocksLeaf?: T | TwoBlocksLeafBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoBlocksLeafBlock_select".
 */
export interface TwoBlocksLeafBlockSelect<T extends boolean = true> {
  type?: T;
  alignment?: T;
  blocks?:
    | T
    | {
        TextCard?: T | TextCardBlockSelect<T>;
        AnnouncementsSection?: T | AnnouncementsSectionBlockSelect<T>;
        ImageBanner?: T | ImageBannerBlockSelect<T>;
        ImageOnlyCard?: T | ImageOnlyCardBlockSelect<T>;
        TestimonialsSpinner?: T | TestimonialsBlockSelect<T>;
        FeaturedComps?: T | FeaturedCompetitionsBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FullWidthBlock_select".
 */
export interface FullWidthBlockSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        TextCard?: T | TextCardBlockSelect<T>;
        AnnouncementsSection?: T | AnnouncementsSectionBlockSelect<T>;
        ImageBanner?: T | ImageBannerBlockSelect<T>;
        ImageOnlyCard?: T | ImageOnlyCardBlockSelect<T>;
        TestimonialsSpinner?: T | TestimonialsBlockSelect<T>;
        FeaturedComps?: T | FeaturedCompetitionsBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-page_select".
 */
export interface AboutUsPageSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        callToAction?:
          | T
          | {
              content?: T;
              contentMarkdown?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        simpleItem?:
          | T
          | {
              title?: T;
              image?: T;
              content?: T;
              contentMarkdown?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              content?: T;
              contentMarkdown?: T;
              quotedPerson?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-page_select".
 */
export interface PrivacyPageSelect<T extends boolean = true> {
  preamble?: T;
  preambleMarkdown?: T;
  blocks?:
    | T
    | {
        paragraph?:
          | T
          | {
              title?: T;
              content?: T;
              contentMarkdown?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disclaimer-page_select".
 */
export interface DisclaimerPageSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        paragraph?:
          | T
          | {
              title?: T;
              content?: T;
              contentMarkdown?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speedcubing-history-page_select".
 */
export interface SpeedcubingHistoryPageSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        paragraph?:
          | T
          | {
              title?: T;
              content?: T;
              contentMarkdown?: T;
              id?: T;
              blockName?: T;
            };
        captionedImage?:
          | T
          | {
              caption?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              content?: T;
              contentMarkdown?: T;
              quotedPerson?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-regulations-page_select".
 */
export interface AboutRegulationsPageSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        paragraph?:
          | T
          | {
              title?: T;
              content?: T;
              contentMarkdown?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents-page_select".
 */
export interface DocumentsPageSelect<T extends boolean = true> {
  documents?:
    | T
    | {
        document?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page_select".
 */
export interface FaqPageSelect<T extends boolean = true> {
  introText?: T;
  introTextMarkdown?: T;
  questions?:
    | T
    | {
        faqQuestion?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logo-page_select".
 */
export interface LogoPageSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        paragraph?:
          | T
          | {
              title?: T;
              content?: T;
              contentMarkdown?: T;
              id?: T;
              blockName?: T;
            };
        logoVariant?:
          | T
          | {
              title?: T;
              caption?: T;
              images?:
                | T
                | {
                    image?: T;
                    darkBackground?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logoDownload?:
          | T
          | {
              url?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
