name 'wca'

depends 'mysql'
depends 'nodejs'
depends 'php-fpm'
depends 'tarsnap'
depends 'logrotate'
depends 'exim4-light'
depends 'brightbox-ruby'
depends 'ssh_known_hosts'
depends 'newrelic-sysmond'
