openapi: 3.1.0
title: WCA API Documentation
summary: Documentation of the WCA API, currently in progress
description: The WCA API allows developers to access data from the WCA using oidc
contact:
  name: WCA Software Team
  url: https://www.worldcubeassociation.org
  email: software@worldcubeassociation.org
version: 0.0.1
servers:
  - url: http://localhost:3000/api/v0
    description: The production API server
paths:
  /competitions/{competitionId}/:
    get:
      summary: Get competition details
      parameters:
        - name: competitionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompetitionInfo'
  /persons/{wca_id}/:
    get:
      summary: Get information for a person
      parameters:
        - name: wca_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonInfo'
  /persons/{wca_id}/results:
    get:
      summary: Get results for a person
      parameters:
        - name: wca_id
          in: path
          required: true
          schema:
            type: string
        - name: event_id
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Results'

  /users/me/permissions:
    get:
      summary: Get user's permissions
      operationId: getUserPermissions
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successfully retrieved permissions
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserPermissions"
        "401":
          description: Unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Person:
      type: object
      properties:
        id:
          type: integer
          example: 267
        name:
          type: string
          example: "Tim Reynolds"
        wca_id:
          type: string
          example: "2005REYN01"
        country_iso2:
          type: string
          example: "US"
        url:
          type: string
          format: uri
          example: "https://www.worldcubeassociation.org/persons/2005REYN01"

    Organizer:
      allOf:
        - $ref: '#/components/schemas/Person'
        - type: object
          properties:
            delegate_status:
              type: string
              example: "regional_delegate"
            email:
              type: string
              format: email
              example: "255@worldcubeassociation.org"
            avatar:
              type: object
              properties:
                url:
                  type: string
                  format: uri
                  example: "https://avatars.worldcubeassociation.org/uploads/user/avatar/2099EXAM/1535183030.jpg"
                thumb_url:
                  type: string
                  format: uri
                  example: "https://avatars.worldcubeassociation.org/uploads/user/avatar/2099EXAM/1535183030_thumb.jpg"

    Rank:
      type: object
      required:
        - id
        - personId
        - eventId
        - best
        - worldRank
        - continentRank
        - countryRank
      properties:
        id:
          type: integer
        personId:
          type: string
        eventId:
          type: string
        best:
          type: integer
        worldRank:
          type: integer
        continentRank:
          type: integer
        countryRank:
          type: integer

    Medals:
      type: object
      required:
        - gold
        - silver
        - bronze
        - total
      properties:
        gold:
          type: integer
        silver:
          type: integer
        bronze:
          type: integer
        total:
          type: integer

    Records:
      type: object
      required:
        - national
        - continental
        - world
        - total
      properties:
        national:
          type: integer
        continental:
          type: integer
        world:
          type: integer
        total:
          type: integer

    PersonInfo:
      type: object
      required:
        - person
        - previous_persons
        - ranks_average
        - ranks_single
        - medals
        - records
        - championship_podiums
      properties:
        person:
          $ref: '#/components/schemas/Person'
        previous_persons:
          type: array
          items:
            type: object
        ranks_single:
          type: array
          items:
            $ref: '#/components/schemas/Rank'
        ranks_average:
          type: array
          items:
            $ref: '#/components/schemas/Rank'
        medals:
          $ref: '#/components/schemas/Medals'
        records:
          $ref: '#/components/schemas/Records'
        championship_podiums:
          type: object
          properties:
            world:
              type: array
              items:
                type: object
            continental:
              type: array
              items:
                type: object
            greater_china:
              type: array
              items:
                type: object
            national:
              type: array
              items:
                type: object

    CompetitionInfo:
      type: object
      required:
        - id
        - name
        - information
        - venue
        - contact
        - registration_open
        - registration_close
        - use_wca_registration
        - guests_enabled
        - announced_at
        - base_entry_fee_lowest_denomination
        - currency_code
        - start_date
        - end_date
        - enable_donations
        - competitor_limit
        - extra_registration_requirements
        - on_the_spot_registration
        - refund_policy_percent
        - refund_policy_limit_date
        - guests_entry_fee_lowest_denomination
        - qualification_results
        - external_registration_page
        - event_restrictions
        - waiting_list_deadline_date
        - event_change_deadline_date
        - guest_entry_status
        - allow_registration_edits
        - allow_registration_without_qualification
        - competitor_can_cancel
        - url
        - website
        - short_name
        - city
        - venue_address
        - venue_details
        - latitude_degrees
        - longitude_degrees
        - country_iso2
        - event_ids
        - main_event_id
        - number_of_bookmarks
        - using_payment_integrations?
        - uses_qualification?
        - uses_cutoff?
        - competition_series_ids
        - registration_full?
        - part_of_competition_series?
        - registration_full_and_accepted?
        - delegates
        - organizers
        - class
      properties:
        id:
          type: string
          example: "WC2003"
        name:
          type: string
          example: "WCA World Championship 2003"
        information:
          type: string
          example: "First WCA World Championship"
        venue:
          type: string
          example: "Toronto"
        contact:
          type: string
          format: uri
          example: "https://www.example.com"
        registration_open:
          type: string
          format: date-time
          example: "2025-01-03T14:00:00.000Z"
        registration_close:
          type: string
          format: date-time
          example: "2025-01-10T14:00:00.000Z"
        use_wca_registration:
          type: boolean
          example: true
        guests_enabled:
          type: boolean
          example: false
        announced_at:
          type: string
          format: date-time
          example: "2024-10-08T22:00:00.000Z"
        base_entry_fee_lowest_denomination:
          type: integer
          example: 12000
        currency_code:
          type: string
          example: "USD"
        start_date:
          type: string
          format: date
          example: "2025-07-03"
        end_date:
          type: string
          format: date
          example: "2025-07-06"
        enable_donations:
          type: boolean
          example: false
        competitor_limit:
          type: integer
          example: 2000
        extra_registration_requirements:
          type: string
          example: ""
        on_the_spot_registration:
          type: boolean
          example: false
        refund_policy_percent:
          type: integer
          example: 50
        refund_policy_limit_date:
          type: string
          format: date-time
          example: "2025-05-15T06:59:00.000Z"
        guests_entry_fee_lowest_denomination:
          type: integer
          example: 1000
        qualification_results:
          type: boolean
          example: true
        event_restrictions:
          type: boolean
          example: false
        cancelled_at:
          type: string
          nullable: true
        waiting_list_deadline_date:
          type: string
          format: date-time
          example: "2025-05-29T06:59:00.000Z"
        event_change_deadline_date:
          type: string
          format: date-time
          example: "2025-05-29T06:59:00.000Z"
        competitor_can_cancel:
          type: string
          example: "not_accepted"
        url:
          type: string
          format: uri
          example: "https://www.worldcubeassociation.org/competitions/WC2003"
        website:
          type: string
          format: uri
          example: "https://cubingusa.org/worlds"
        city:
          type: string
          example: "Seattle, Washington"
        latitude_degrees:
          type: number
          format: float
          example: 47.611387
        longitude_degrees:
          type: number
          format: float
          example: -122.332554
        country_iso2:
          type: string
          example: "US"
        event_ids:
          type: array
          items:
            type: string
          example: [ "333" ]
        registration_full?:
          type: boolean
          example: true
        delegates:
          type: array
          items:
            $ref: '#/components/schemas/Person'
        organizers:
          type: array
          items:
            $ref: '#/components/schemas/Organizer'

    CompetitionPermissions:
      oneOf:
        - type: array
          items:
            type: string
        - type: string
          format: "Wildcard"
          enum: "*"

    UserPermissions:
      type: object
      required:
        - can_access_panels
        - can_administer_competitions
        - can_attend_competitions
        - can_create_groups
        - can_edit_delegate_report
        - can_edit_groups
        - can_organize_competitions
        - can_read_groups_current
        - can_read_groups_past
        - can_request_to_edit_others_profile
        - can_view_delegate_admin_page
        - can_view_delegate_report
      properties:
        can_attend_competitions:
          type: object
          required:
            - scope
          properties:
            scope:
              $ref: "#/components/schemas/CompetitionPermissions"
            until:
              type: string
              format: date-time
              nullable: true
        can_organize_competitions:
          type: object
          required:
            - scope
          properties:
            scope:
              $ref: "#/components/schemas/CompetitionPermissions"
        can_administer_competitions:
          type: object
          required:
            - scope
          properties:
            scope:
              $ref: "#/components/schemas/CompetitionPermissions"
        can_view_delegate_admin_page:
          type: object
          required:
            - scope
          properties:
            scope:
              $ref: "#/components/schemas/CompetitionPermissions"
        can_view_delegate_report:
          type: object
          required:
            - scope
          properties:
            scope:
              $ref: "#/components/schemas/CompetitionPermissions"
        can_edit_delegate_report:
          type: object
          required:
            - scope
          properties:
            scope:
              $ref: "#/components/schemas/CompetitionPermissions"
        can_create_groups:
          type: object
          required:
            - scope
          properties:
            scope:
              type: array
              items:
                type: string
        can_read_groups_current:
          type: object
          required:
            - scope
          properties:
            scope:
              type: array
              items:
                type: string
        can_read_groups_past:
          type: object
          required:
            - scope
          properties:
            scope:
              type: array
              items:
                type: string
        can_edit_groups:
          type: object
          required:
            - scope
          properties:
            scope:
              type: array
              items:
                type: string
        can_access_panels:
          type: object
          required:
            - scope
          properties:
            scope:
              type: array
              items:
                type: string
        can_request_to_edit_others_profile:
          type: object
          required:
            - scope
          properties:
            scope:
              oneOf:
                - type: array
                  items:
                    type: string
                - type: string
                  format: "Wildcard"
                  enum: "*"

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
          format: email

    Results:
      type: array
      items:
        $ref: "#/components/schemas/Result"

    Result:
      type: object
      required:
        - id
        - pos
        - best
        - average
        - name
        - country_iso2
        - competition_id
        - event_id
        - round_type_id
        - format_id
        - wca_id
        - attempts
        - best_index
        - worst_index
        - regional_single_record
        - regional_average_record
      properties:
        id:
          type: integer
        pos:
          type: integer
        best:
          type: integer
        average:
          type: integer
        name:
          type: string
        country_iso2:
          type: string
        competition_id:
          type: string
        event_id:
          type: string
        round_type_id:
          type: string
        format_id:
          type: string
        wca_id:
          type: string
        attempts:
          type: array
          items:
            type: integer
        best_index:
          type: integer
        worst_index:
          type: integer
        regional_single_record:
          type: string
          nullable: true
        regional_average_record:
          type: string
          nullable: true

    PersonalRecord:
      type: object
      properties:
        eventId:
          type: string
        bestTime:
          type: integer
          description: Best performance in milliseconds
        averageTime:
          type: integer
          description: Average performance in milliseconds

    Event:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
