inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  Exclude:
    - 'WcaOnRails/node_modules/**/*'
    - 'WcaOnRails/bin/**/*'
    - 'WcaOnRails/vendor/**/*'
    # This file is provided as-is by Discourse
    - 'WcaOnRails/lib/single_sign_on.rb'

Bundler/OrderedGems:
  Enabled: false

Lint/EmptyWhen:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/Alias:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/RedundantSelf:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/StringLiterals:
  # EnforcedStyle: double_quotes
  Enabled: false

Style/TrailingCommaInArguments:
  # If `comma`, the cop requires a comma after the last argument, but only for
  # parenthesized method calls where each argument is on its own line.
  # If `consistent_comma`, the cop requires a comma after the last argument,
  # for all parenthesized method calls with arguments.
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  # If `comma`, the cop requires a comma after the last argument, but only for
  # parenthesized method calls where each argument is on its own line.
  # If `consistent_comma`, the cop requires a comma after the last argument,
  # for all parenthesized method calls with arguments.
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  # If `comma`, the cop requires a comma after the last item in an array or
  # hash, but only when each item is on its own line.
  # If `consistent_comma`, the cop requires a comma after the last item of all
  # non-empty array and hash literals.
  EnforcedStyleForMultiline: comma

Style/GuardClause:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 23
  Exclude:
    - 'WcaOnRails/app/controllers/competitions_controller.rb'
    - 'WcaOnRails/app/controllers/registrations_controller.rb'
    - 'WcaOnRails/app/jobs/sync_mailing_lists_job.rb'
    - 'WcaOnRails/app/models/competition.rb'
    - 'WcaOnRails/lib/results_validators/*.rb'

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Max: 25
  Exclude:
    - 'WcaOnRails/app/controllers/competitions_controller.rb'
    - 'WcaOnRails/app/controllers/registrations_controller.rb'
    - 'WcaOnRails/app/jobs/sync_mailing_lists_job.rb'
    - 'WcaOnRails/app/models/competition.rb'
    - 'WcaOnRails/lib/results_validators/*.rb'

Layout/LineLength:
  Max: 245

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/IfInsideElse:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RedundantParentheses:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Layout/SpaceAroundOperators:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/BlockParameterName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/YodaCondition:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/BeginEndAlignment:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/EmptyFile:
  Enabled: true
  Exclude:
    - 'WcaOnRails/db/seeds.rb'

Lint/FloatComparison:
  Enabled: true

Lint/HashCompareByIdentity:
  Enabled: true

Lint/IdentityComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: false

Lint/RedundantSafeNavigation:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Lint/UselessTimes:
  Enabled: true

Style/AccessorGrouping:
  Enabled: false

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ClassEqualityComparison:
  Enabled: true

Style/CombinableLoops:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/KeywordParametersOrder:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantSelfAssignment:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/SlicingWithRange:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Layout/SpaceBeforeBrackets:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: false

Lint/EmptyClass:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/SymbolConversion:
  Enabled: false

Lint/ToEnumArguments:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/EndlessMethod:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: false

Style/NilLambda:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Style/SwapValues:
  Enabled: true

Naming/VariableNumber:
  Enabled: false

Gemspec/DateAssignment:
  Enabled: true

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Lint/AmbiguousRange:
  Enabled: true

Lint/EmptyInPattern:
  Enabled: true

Naming/InclusiveLanguage:
  Enabled: true
  Exclude:
    - 'WcaOnRails/config/**/*'

Style/HashConversion:
  Enabled: true

Style/InPatternThen:
  Enabled: true

Style/MultilineInPatternThen:
  Enabled: true

Style/QuotedSymbols:
  Enabled: false

Style/RedundantSelfAssignmentBranch:
  Enabled: true

Style/StringChars:
  Enabled: true

Style/CommentAnnotation:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: true

Lint/AmbiguousOperatorPrecedence:
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true

Lint/RefinementImportMethods:
  Enabled: true

Lint/RequireRelativeSelfPath:
  Enabled: true

Lint/UselessRuby2Keywords:
  Enabled: true

Naming/BlockForwarding:
  Enabled: true

Security/CompoundHash:
  Enabled: true

Security/IoMethods:
  Enabled: true

Style/FetchEnvVar:
  Enabled: true

Style/FileRead:
  Enabled: true

Style/FileWrite:
  Enabled: true

Style/MapToHash:
  Enabled: true

Style/NestedFileDirname:
  Enabled: true

Style/NumberedParameters:
  Enabled: true

Style/NumberedParametersLimit:
  Enabled: true

Style/ObjectThen:
  Enabled: true

Style/OpenStructUse:
  Enabled: true
  Exclude:
    - 'WcaOnRails/spec/lib/middlewares/warden_user_logger_spec.rb'

Style/RedundantInitialize:
  Enabled: true

Style/SelectByRegexp:
  Enabled: true
