approvedGitRepositories:
  - "https://github.com/thewca/*"

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 1d

npmPreapprovedPackages:
  - "react"
  - "react-dom"
  - "next"
  - "payload"
  - "@payloadcms/*"
