version: "3"
services:
  wca_on_rails:
    build:
      context: WcaOnRails
    network_mode: host
    working_dir: /app/WcaOnRails
    volumes:
      - .:/app
      - gems_volume:/usr/local/bundle
    tty: true
    # First, install Ruby and Node dependencies
    # Start the server and bind to 0.0.0.0 (vs 127.0.0.1) so Docker's port mappings work correctly
    command: >
      bash -c 'bundle install && yarn install &&
      bin/rails server -b 0.0.0.0'

volumes:
  gems_volume:
    driver: local
