FROM ruby:3.4.6

WORKDIR /rails

ENV DEBIAN_FRONTEND noninteractive

# Add PPA needed to install nodejs.
# From: https://github.com/nodesource/distributions#debian-and-ubuntu-based-distributions
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      ca-certificates \
      curl \
      gnupg

ARG NODE_MAJOR=24
RUN curl -fsSL https://deb.nodesource.com/setup_${NODE_MAJOR}.x | bash && \
    apt-get install nodejs

# Enable 'corepack' feature that lets NPM download the package manager on-the-fly as required.
RUN corepack enable

# Copy a file of our development runtime dependencies into the image for initial install
COPY packages.dev.txt /tmp/packages.txt
COPY package-install.dev.sh /tmp/package-install.sh

RUN /tmp/package-install.sh /tmp/packages.txt

RUN gem update --system && gem install bundler

EXPOSE 3000
