# frozen_string_literal: true
Country.create(id: "Afghanistan", name: "Afghanistan", continentId: "_Asia", iso2: "AF")
Country.create(id: "Albania", name: "Albania", continentId: "_Europe", iso2: "AL")
Country.create(id: "Algeria", name: "Algeria", continentId: "_Africa", iso2: "DZ")
Country.create(id: "Andorra", name: "Andorra", continentId: "_Europe", iso2: "AD")
Country.create(id: "Angola", name: "Angola", continentId: "_Africa", iso2: "AO")
Country.create(id: "Anguilla", name: "Anguilla", continentId: "_North America", iso2: "AI")
Country.create(id: "Antigua", name: "Antigua", continentId: "_North America", iso2: "AG")
Country.create(id: "Argentina", name: "Argentina", continentId: "_South America", iso2: "AR")
Country.create(id: "Armenia", name: "Armenia", continentId: "_Europe", iso2: "AM")
Country.create(id: "Aruba", name: "Aruba", continentId: "_North America", iso2: "AW")
Country.create(id: "Australia", name: "Australia", continentId: "_Oceania", iso2: "AU")
Country.create(id: "Austria", name: "Austria", continentId: "_Europe", iso2: "AT")
Country.create(id: "Azerbaijan", name: "Azerbaijan", continentId: "_Europe", iso2: "AZ")
Country.create(id: "Bahamas", name: "Bahamas", continentId: "_North America", iso2: "BS")
Country.create(id: "Bahrain", name: "Bahrain", continentId: "_Asia", iso2: "BH")
Country.create(id: "Bangladesh", name: "Bangladesh", continentId: "_Asia", iso2: "BD")
Country.create(id: "Barbados", name: "Barbados", continentId: "_North America", iso2: "BB")
Country.create(id: "Belarus", name: "Belarus", continentId: "_Europe", iso2: "BY")
Country.create(id: "Belgium", name: "Belgium", continentId: "_Europe", iso2: "BE")
Country.create(id: "Belize", name: "Belize", continentId: "_North America", iso2: "BZ")
Country.create(id: "Benin", name: "Benin", continentId: "_Africa", iso2: "BJ")
Country.create(id: "Bhutan", name: "Bhutan", continentId: "_Asia", iso2: "BT")
Country.create(id: "Bolivia", name: "Bolivia", continentId: "_South America", iso2: "BO")
Country.create(id: "Bosnia and Herzegovina", name: "Bosnia and Herzegovina", continentId: "_Europe", iso2: "BA")
Country.create(id: "Botswana", name: "Botswana", continentId: "_Africa", iso2: "BW")
Country.create(id: "Brazil", name: "Brazil", continentId: "_South America", iso2: "BR")
Country.create(id: "British Virgin Islands", name: "British Virgin Islands", continentId: "_North America", iso2: "VG")
Country.create(id: "Brunei", name: "Brunei", continentId: "_Asia", iso2: "BN")
Country.create(id: "Bulgaria", name: "Bulgaria", continentId: "_Europe", iso2: "BG")
Country.create(id: "Burkina Faso", name: "Burkina Faso", continentId: "_Africa", iso2: "BF")
Country.create(id: "Cambodia", name: "Cambodia", continentId: "_Asia", iso2: "KH")
Country.create(id: "Cameroon", name: "Cameroon", continentId: "_Africa", iso2: "CM")
Country.create(id: "Canada", name: "Canada", continentId: "_North America", iso2: "CA")
Country.create(id: "Central African Republic", name: "Central African Republic", continentId: "_Africa", iso2: "CF")
Country.create(id: "Chad", name: "Chad", continentId: "_Africa", iso2: "TD")
Country.create(id: "Chile", name: "Chile", continentId: "_South America", iso2: "CL")
Country.create(id: "China", name: "China", continentId: "_Asia", iso2: "CN")
Country.create(id: "Colombia", name: "Colombia", continentId: "_South America", iso2: "CO")
Country.create(id: "Comoros", name: "Comoros", continentId: "_Africa", iso2: "KM")
Country.create(id: "Congo", name: "Congo", continentId: "_Africa", iso2: "CG")
Country.create(id: "Cook Islands", name: "Cook Islands", continentId: "_Asia", iso2: "CK")
Country.create(id: "Costa Rica", name: "Costa Rica", continentId: "_North America", iso2: "CR")
Country.create(id: "Cote d_Ivoire", name: "Cote d'Ivoire", continentId: "_Africa", iso2: "CI")
Country.create(id: "Croatia", name: "Croatia", continentId: "_Europe", iso2: "HR")
Country.create(id: "Cuba", name: "Cuba", continentId: "_North America", iso2: "CU")
Country.create(id: "Cyprus", name: "Cyprus", continentId: "_Europe", iso2: "CY")
Country.create(id: "Czech Republic", name: "Czech Republic", continentId: "_Europe", iso2: "CZ")
Country.create(id: "Denmark", name: "Denmark", continentId: "_Europe", iso2: "DK")
Country.create(id: "Djibouti", name: "Djibouti", continentId: "_Africa", iso2: "DJ")
Country.create(id: "Dominica", name: "Dominica", continentId: "_North America", iso2: "DM")
Country.create(id: "Dominican Republic", name: "Dominican Republic", continentId: "_North America", iso2: "DO")
Country.create(id: "DR Congo", name: "DR Congo", continentId: "_Africa", iso2: "CD")
Country.create(id: "Ecuador", name: "Ecuador", continentId: "_South America", iso2: "EC")
Country.create(id: "Egypt", name: "Egypt", continentId: "_Africa", iso2: "EG")
Country.create(id: "El Salvador", name: "El Salvador", continentId: "_North America", iso2: "SV")
Country.create(id: "Equatorial Guinea", name: "Equatorial Guinea", continentId: "_Africa", iso2: "GQ")
Country.create(id: "Eritrea", name: "Eritrea", continentId: "_Africa", iso2: "ER")
Country.create(id: "Estonia", name: "Estonia", continentId: "_Europe", iso2: "EE")
Country.create(id: "Ethiopia", name: "Ethiopia", continentId: "_Africa", iso2: "ET")
Country.create(id: "Fiji", name: "Fiji", continentId: "_Oceania", iso2: "FJ")
Country.create(id: "Finland", name: "Finland", continentId: "_Europe", iso2: "FI")
Country.create(id: "France", name: "France", continentId: "_Europe", iso2: "FR")
Country.create(id: "French Guiana", name: "French Guiana", continentId: "_South America", iso2: "GF")
Country.create(id: "French Polynesia", name: "French Polynesia", continentId: "_Oceania", iso2: "PF")
Country.create(id: "Gabon", name: "Gabon", continentId: "_Africa", iso2: "GA")
Country.create(id: "Gambia", name: "Gambia", continentId: "_Africa", iso2: "GM")
Country.create(id: "Georgia", name: "Georgia", continentId: "_Europe", iso2: "GE")
Country.create(id: "Germany", name: "Germany", continentId: "_Europe", iso2: "DE")
Country.create(id: "Ghana", name: "Ghana", continentId: "_Africa", iso2: "GH")
Country.create(id: "Greece", name: "Greece", continentId: "_Europe", iso2: "GR")
Country.create(id: "Grenada", name: "Grenada", continentId: "_North America", iso2: "GD")
Country.create(id: "Guatemala", name: "Guatemala", continentId: "_North America", iso2: "GT")
Country.create(id: "Guernsey", name: "Guernsey", continentId: "_Europe", iso2: "GG")
Country.create(id: "Guinea", name: "Guinea", continentId: "_Africa", iso2: "GN")
Country.create(id: "Guyana", name: "Guyana", continentId: "_South America", iso2: "GY")
Country.create(id: "Haiti", name: "Haiti", continentId: "_North America", iso2: "HT")
Country.create(id: "Honduras", name: "Honduras", continentId: "_North America", iso2: "HN")
Country.create(id: "Hong Kong", name: "Hong Kong", continentId: "_Asia", iso2: "HK")
Country.create(id: "Hungary", name: "Hungary", continentId: "_Europe", iso2: "HU")
Country.create(id: "Iceland", name: "Iceland", continentId: "_Europe", iso2: "IS")
Country.create(id: "India", name: "India", continentId: "_Asia", iso2: "IN")
Country.create(id: "Indonesia", name: "Indonesia", continentId: "_Asia", iso2: "ID")
Country.create(id: "Iran", name: "Iran", continentId: "_Asia", iso2: "IR")
Country.create(id: "Iraq", name: "Iraq", continentId: "_Asia", iso2: "IQ")
Country.create(id: "Ireland", name: "Ireland", continentId: "_Europe", iso2: "IE")
Country.create(id: "Isle of Man", name: "Isle of Man", continentId: "_Europe", iso2: "IM")
Country.create(id: "Israel", name: "Israel", continentId: "_Europe", iso2: "IL")
Country.create(id: "Italy", name: "Italy", continentId: "_Europe", iso2: "IT")
Country.create(id: "Jamaica", name: "Jamaica", continentId: "_North America", iso2: "JM")
Country.create(id: "Japan", name: "Japan", continentId: "_Asia", iso2: "JP")
Country.create(id: "Jordan", name: "Jordan", continentId: "_Asia", iso2: "JO")
Country.create(id: "Kazakhstan", name: "Kazakhstan", continentId: "_Asia", iso2: "KZ")
Country.create(id: "Kenya", name: "Kenya", continentId: "_Africa", iso2: "KE")
Country.create(id: "Kiribati", name: "Kiribati", continentId: "_Oceania", iso2: "KI")
Country.create(id: "Korea", name: "Korea", continentId: "_Asia", iso2: "KR")
Country.create(id: "Kosovo", name: "Kosovo", continentId: "_Europe", iso2: "XK")
Country.create(id: "Kuwait", name: "Kuwait", continentId: "_Asia", iso2: "KW")
Country.create(id: "Laos", name: "Laos", continentId: "_Asia", iso2: "LA")
Country.create(id: "Latvia", name: "Latvia", continentId: "_Europe", iso2: "LV")
Country.create(id: "Lebanon", name: "Lebanon", continentId: "_Asia", iso2: "LB")
Country.create(id: "Lesotho", name: "Lesotho", continentId: "_Africa", iso2: "LS")
Country.create(id: "Liberia", name: "Liberia", continentId: "_Africa", iso2: "LR")
Country.create(id: "Libya", name: "Libya", continentId: "_Africa", iso2: "LY")
Country.create(id: "Liechtenstein", name: "Liechtenstein", continentId: "_Europe", iso2: "LI")
Country.create(id: "Lithuania", name: "Lithuania", continentId: "_Europe", iso2: "LT")
Country.create(id: "Luxembourg", name: "Luxembourg", continentId: "_Europe", iso2: "LU")
Country.create(id: "Macau", name: "Macau", continentId: "_Asia", iso2: "MO")
Country.create(id: "Macedonia", name: "Macedonia", continentId: "_Europe", iso2: "MK")
Country.create(id: "Madagascar", name: "Madagascar", continentId: "_Africa", iso2: "MG")
Country.create(id: "Malawi", name: "Malawi", continentId: "_Africa", iso2: "MW")
Country.create(id: "Malaysia", name: "Malaysia", continentId: "_Asia", iso2: "MY")
Country.create(id: "Mali", name: "Mali", continentId: "_Africa", iso2: "ML")
Country.create(id: "Malta", name: "Malta", continentId: "_Europe", iso2: "MT")
Country.create(id: "Marshall Islands", name: "Marshall Islands", continentId: "_Oceania", iso2: "MH")
Country.create(id: "Mauritania", name: "Mauritania", continentId: "_Africa", iso2: "MR")
Country.create(id: "Mauritius", name: "Mauritius", continentId: "_Africa", iso2: "MU")
Country.create(id: "Mayotte", name: "Mayotte", continentId: "_Africa", iso2: "YT")
Country.create(id: "Mexico", name: "Mexico", continentId: "_North America", iso2: "MX")
Country.create(id: "Moldova", name: "Moldova", continentId: "_Europe", iso2: "MD")
Country.create(id: "Monaco", name: "Monaco", continentId: "_Europe", iso2: "MC")
Country.create(id: "Mongolia", name: "Mongolia", continentId: "_Asia", iso2: "MN")
Country.create(id: "Montenegro", name: "Montenegro", continentId: "_Europe", iso2: "ME")
Country.create(id: "Morocco", name: "Morocco", continentId: "_Africa", iso2: "MA")
Country.create(id: "Mozambique", name: "Mozambique", continentId: "_Africa", iso2: "MZ")
Country.create(id: "Myanmar", name: "Myanmar", continentId: "_Asia", iso2: "MM")
Country.create(id: "Namibia", name: "Namibia", continentId: "_Africa", iso2: "NA")
Country.create(id: "Nauru", name: "Nauru", continentId: "_Oceania", iso2: "NR")
Country.create(id: "Nepal", name: "Nepal", continentId: "_Asia", iso2: "NP")
Country.create(id: "Netherlands", name: "Netherlands", continentId: "_Europe", iso2: "NL")
Country.create(id: "New Caledonia", name: "New Caledonia", continentId: "_Oceania", iso2: "NC")
Country.create(id: "New Zealand", name: "New Zealand", continentId: "_Oceania", iso2: "NZ")
Country.create(id: "Nicaragua", name: "Nicaragua", continentId: "_North America", iso2: "NI")
Country.create(id: "Niger", name: "Niger", continentId: "_Africa", iso2: "NE")
Country.create(id: "Nigeria", name: "Nigeria", continentId: "_Africa", iso2: "NG")
Country.create(id: "Niue", name: "Niue", continentId: "_Oceania", iso2: "NU")
Country.create(id: "North Korea", name: "North Korea", continentId: "_Asia", iso2: "KP")
Country.create(id: "Norway", name: "Norway", continentId: "_Europe", iso2: "NO")
Country.create(id: "Oman", name: "Oman", continentId: "_Asia", iso2: "OM")
Country.create(id: "Pakistan", name: "Pakistan", continentId: "_Asia", iso2: "PK")
Country.create(id: "Palestine", name: "Palestine", continentId: "_Asia", iso2: "PS")
Country.create(id: "Panama", name: "Panama", continentId: "_North America", iso2: "PA")
Country.create(id: "Papua New Guinea", name: "Papua New Guinea", continentId: "_Oceania", iso2: "PG")
Country.create(id: "Paraguay", name: "Paraguay", continentId: "_South America", iso2: "PY")
Country.create(id: "Peru", name: "Peru", continentId: "_South America", iso2: "PE")
Country.create(id: "Philippines", name: "Philippines", continentId: "_Asia", iso2: "PH")
Country.create(id: "Pitcairn Islands", name: "Pitcairn Islands", continentId: "_Oceania", iso2: "PN")
Country.create(id: "Poland", name: "Poland", continentId: "_Europe", iso2: "PL")
Country.create(id: "Portugal", name: "Portugal", continentId: "_Europe", iso2: "PT")
Country.create(id: "Puerto Rico", name: "Puerto Rico", continentId: "_North America", iso2: "PR")
Country.create(id: "Qatar", name: "Qatar", continentId: "_Asia", iso2: "QA")
Country.create(id: "Romania", name: "Romania", continentId: "_Europe", iso2: "RO")
Country.create(id: "Russia", name: "Russia", continentId: "_Europe", iso2: "RU")
Country.create(id: "Saint Kitts and Nevis", name: "Saint Kitts and Nevis", continentId: "_North America", iso2: "KN")
Country.create(id: "Saint Lucia", name: "Saint Lucia", continentId: "_North America", iso2: "LC")
Country.create(id: "Saint Vincent and the Grenadines", name: "Saint Vincent and the Grenadines", continentId: "_North America", iso2: "VC")
Country.create(id: "Samoa", name: "Samoa", continentId: "_Oceania", iso2: "WS")
Country.create(id: "San Marino", name: "San Marino", continentId: "_Europe", iso2: "SM")
Country.create(id: "Sao Tome and Principe", name: "Sao Tome and Principe", continentId: "_Africa", iso2: "ST")
Country.create(id: "Saudi Arabia", name: "Saudi Arabia", continentId: "_Asia", iso2: "SA")
Country.create(id: "Senegal", name: "Senegal", continentId: "_Africa", iso2: "SN")
Country.create(id: "Serbia", name: "Serbia", continentId: "_Europe", iso2: "RS")
Country.create(id: "Sierra Leone", name: "Sierra Leone", continentId: "_Africa", iso2: "SL")
Country.create(id: "Singapore", name: "Singapore", continentId: "_Asia", iso2: "SG")
Country.create(id: "Slovakia", name: "Slovakia", continentId: "_Europe", iso2: "SK")
Country.create(id: "Slovenia", name: "Slovenia", continentId: "_Europe", iso2: "SI")
Country.create(id: "Solomon Islands", name: "Solomon Islands", continentId: "_Oceania", iso2: "SB")
Country.create(id: "Somalia", name: "Somalia", continentId: "_Africa", iso2: "SO")
Country.create(id: "South Africa", name: "South Africa", continentId: "_Africa", iso2: "ZA")
Country.create(id: "South Sudan", name: "South Sudan", continentId: "_Africa", iso2: "SS")
Country.create(id: "Spain", name: "Spain", continentId: "_Europe", iso2: "ES")
Country.create(id: "Sri Lanka", name: "Sri Lanka", continentId: "_Asia", iso2: "LK")
Country.create(id: "Sudan", name: "Sudan", continentId: "_Africa", iso2: "SD")
Country.create(id: "Suriname", name: "Suriname", continentId: "_South America", iso2: "SR")
Country.create(id: "Swaziland", name: "Swaziland", continentId: "_Africa", iso2: "SZ")
Country.create(id: "Sweden", name: "Sweden", continentId: "_Europe", iso2: "SE")
Country.create(id: "Switzerland", name: "Switzerland", continentId: "_Europe", iso2: "CH")
Country.create(id: "Syria", name: "Syria", continentId: "_Asia", iso2: "SY")
Country.create(id: "Taiwan", name: "Taiwan", continentId: "_Asia", iso2: "TW")
Country.create(id: "Tanzania", name: "Tanzania", continentId: "_Africa", iso2: "TZ")
Country.create(id: "Thailand", name: "Thailand", continentId: "_Asia", iso2: "TH")
Country.create(id: "Togo", name: "Togo", continentId: "_Africa", iso2: "TG")
Country.create(id: "Tonga", name: "Tonga", continentId: "_Oceania", iso2: "TO")
Country.create(id: "Trinidad and Tobago", name: "Trinidad and Tobago", continentId: "_North America", iso2: "TT")
Country.create(id: "Tunisia", name: "Tunisia", continentId: "_Africa", iso2: "TN")
Country.create(id: "Turkey", name: "Turkey", continentId: "_Europe", iso2: "TR")
Country.create(id: "Turks and Caicos Islands", name: "Turks and Caicos Islands", continentId: "_North America", iso2: "TC")
Country.create(id: "Tuvalu", name: "Tuvalu", continentId: "_Oceania", iso2: "TV")
Country.create(id: "Uganda", name: "Uganda", continentId: "_Africa", iso2: "UG")
Country.create(id: "Ukraine", name: "Ukraine", continentId: "_Europe", iso2: "UA")
Country.create(id: "United Arab Emirates", name: "United Arab Emirates", continentId: "_Asia", iso2: "AE")
Country.create(id: "United Kingdom", name: "United Kingdom", continentId: "_Europe", iso2: "GB")
Country.create(id: "Uruguay", name: "Uruguay", continentId: "_South America", iso2: "UY")
Country.create(id: "USA", name: "USA", continentId: "_North America", iso2: "US")
Country.create(id: "Uzbekistan", name: "Uzbekistan", continentId: "_Asia", iso2: "UZ")
Country.create(id: "Vanuatu", name: "Vanuatu", continentId: "_Oceania", iso2: "VU")
Country.create(id: "Venezuela", name: "Venezuela", continentId: "_South America", iso2: "VE")
Country.create(id: "Vietnam", name: "Vietnam", continentId: "_Asia", iso2: "VN")
Country.create(id: "XA", name: "Multiple Countries (Asia)", continentId: "_Asia", iso2: "XA")
Country.create(id: "XE", name: "Multiple Countries (Europe)", continentId: "_Europe", iso2: "XE")
Country.create(id: "XS", name: "Multiple Countries (South America)", continentId: "_South America", iso2: "XS")
Country.create(id: "Yemen", name: "Yemen", continentId: "_Asia", iso2: "YE")
Country.create(id: "Zambia", name: "Zambia", continentId: "_Africa", iso2: "ZM")
Country.create(id: "Zimbabwe", name: "Zimbabwe", continentId: "_Africa", iso2: "ZW")
