# frozen_string_literal: true

sql = "INSERT INTO `Countries` (`id`, `name`, `continentId`, `iso2`) VALUES
('Afghanistan', 'Afghanistan', '_Asia', 'AF'),
('Albania', 'Albania', '_Europe', 'AL'),
('Algeria', 'Algeria', '_Africa', 'DZ'),
('Andorra', 'Andorra', '_Europe', 'AD'),
('Angola', 'Angola', '_Africa', 'AO'),
('Anguilla', 'Anguilla', '_North America', 'AI'),
('Antigua', 'Antigua', '_North America', 'AG'),
('Argentina', 'Argentina', '_South America', 'AR'),
('Armenia', 'Armenia', '_Europe', 'AM'),
('Aruba', 'Aruba', '_North America', 'AW'),
('Australia', 'Australia', '_Oceania', 'AU'),
('Austria', 'Austria', '_Europe', 'AT'),
('Azerbaijan', 'Azerbaijan', '_Europe', 'AZ'),
('Bahamas', 'Bahamas', '_North America', 'BS'),
('Bahrain', 'Bahrain', '_Asia', 'BH'),
('Bangladesh', 'Bangladesh', '_Asia', 'BD'),
('Barbados', 'Barbados', '_North America', 'BB'),
('Belarus', 'Belarus', '_Europe', 'BY'),
('Belgium', 'Belgium', '_Europe', 'BE'),
('Belize', 'Belize', '_North America', 'BZ'),
('Benin', 'Benin', '_Africa', 'BJ'),
('Bhutan', 'Bhutan', '_Asia', 'BT'),
('Bolivia', 'Bolivia', '_South America', 'BO'),
('Bosnia and Herzegovina', 'Bosnia and Herzegovina', '_Europe', 'BA'),
('Botswana', 'Botswana', '_Africa', 'BW'),
('Brazil', 'Brazil', '_South America', 'BR'),
('British Virgin Islands', 'British Virgin Islands', '_North America', 'VG'),
('Brunei', 'Brunei', '_Asia', 'BN'),
('Bulgaria', 'Bulgaria', '_Europe', 'BG'),
('Burkina Faso', 'Burkina Faso', '_Africa', 'BF'),
('Cambodia', 'Cambodia', '_Asia', 'KH'),
('Cameroon', 'Cameroon', '_Africa', 'CM'),
('Canada', 'Canada', '_North America', 'CA'),
('Central African Republic', 'Central African Republic', '_Africa', 'CF'),
('Chad', 'Chad', '_Africa', 'TD'),
('Chile', 'Chile', '_South America', 'CL'),
('China', 'China', '_Asia', 'CN'),
('Colombia', 'Colombia', '_South America', 'CO'),
('Comoros', 'Comoros', '_Africa', 'KM'),
('Congo', 'Congo', '_Africa', 'CG'),
('Cook Islands', 'Cook Islands', '_Asia', 'CK'),
('Costa Rica', 'Costa Rica', '_North America', 'CR'),
('Cote d_Ivoire', 'Cote d''Ivoire', '_Africa', 'CI'),
('Croatia', 'Croatia', '_Europe', 'HR'),
('Cuba', 'Cuba', '_North America', 'CU'),
('Cyprus', 'Cyprus', '_Europe', 'CY'),
('Czech Republic', 'Czech Republic', '_Europe', 'CZ'),
('Denmark', 'Denmark', '_Europe', 'DK'),
('Djibouti', 'Djibouti', '_Africa', 'DJ'),
('Dominica', 'Dominica', '_North America', 'DM'),
('Dominican Republic', 'Dominican Republic', '_North America', 'DO'),
('DR Congo', 'DR Congo', '_Africa', 'CD'),
('Ecuador', 'Ecuador', '_South America', 'EC'),
('Egypt', 'Egypt', '_Africa', 'EG'),
('El Salvador', 'El Salvador', '_North America', 'SV'),
('Equatorial Guinea', 'Equatorial Guinea', '_Africa', 'GQ'),
('Eritrea', 'Eritrea', '_Africa', 'ER'),
('Estonia', 'Estonia', '_Europe', 'EE'),
('Ethiopia', 'Ethiopia', '_Africa', 'ET'),
('Fiji', 'Fiji', '_Oceania', 'FJ'),
('Finland', 'Finland', '_Europe', 'FI'),
('France', 'France', '_Europe', 'FR'),
('French Guiana', 'French Guiana', '_South America', 'GF'),
('French Polynesia', 'French Polynesia', '_Oceania', 'PF'),
('Gabon', 'Gabon', '_Africa', 'GA'),
('Gambia', 'Gambia', '_Africa', 'GM'),
('Georgia', 'Georgia', '_Europe', 'GE'),
('Germany', 'Germany', '_Europe', 'DE'),
('Ghana', 'Ghana', '_Africa', 'GH'),
('Greece', 'Greece', '_Europe', 'GR'),
('Grenada', 'Grenada', '_North America', 'GD'),
('Guatemala', 'Guatemala', '_North America', 'GT'),
('Guernsey', 'Guernsey', '_Europe', 'GG'),
('Guinea', 'Guinea', '_Africa', 'GN'),
('Guyana', 'Guyana', '_South America', 'GY'),
('Haiti', 'Haiti', '_North America', 'HT'),
('Honduras', 'Honduras', '_North America', 'HN'),
('Hong Kong', 'Hong Kong', '_Asia', 'HK'),
('Hungary', 'Hungary', '_Europe', 'HU'),
('Iceland', 'Iceland', '_Europe', 'IS'),
('India', 'India', '_Asia', 'IN'),
('Indonesia', 'Indonesia', '_Asia', 'ID'),
('Iran', 'Iran', '_Asia', 'IR'),
('Iraq', 'Iraq', '_Asia', 'IQ'),
('Ireland', 'Ireland', '_Europe', 'IE'),
('Isle of Man', 'Isle of Man', '_Europe', 'IM'),
('Israel', 'Israel', '_Europe', 'IL'),
('Italy', 'Italy', '_Europe', 'IT'),
('Jamaica', 'Jamaica', '_North America', 'JM'),
('Japan', 'Japan', '_Asia', 'JP'),
('Jordan', 'Jordan', '_Asia', 'JO'),
('Kazakhstan', 'Kazakhstan', '_Asia', 'KZ'),
('Kenya', 'Kenya', '_Africa', 'KE'),
('Kiribati', 'Kiribati', '_Oceania', 'KI'),
('Korea', 'Korea', '_Asia', 'KR'),
('Kosovo', 'Kosovo', '_Europe', 'XK'),
('Kuwait', 'Kuwait', '_Asia', 'KW'),
('Laos', 'Laos', '_Asia', 'LA'),
('Latvia', 'Latvia', '_Europe', 'LV'),
('Lebanon', 'Lebanon', '_Asia', 'LB'),
('Lesotho', 'Lesotho', '_Africa', 'LS'),
('Liberia', 'Liberia', '_Africa', 'LR'),
('Libya', 'Libya', '_Africa', 'LY'),
('Liechtenstein', 'Liechtenstein', '_Europe', 'LI'),
('Lithuania', 'Lithuania', '_Europe', 'LT'),
('Luxembourg', 'Luxembourg', '_Europe', 'LU'),
('Macau', 'Macau', '_Asia', 'MO'),
('Macedonia', 'Macedonia', '_Europe', 'MK'),
('Madagascar', 'Madagascar', '_Africa', 'MG'),
('Malawi', 'Malawi', '_Africa', 'MW'),
('Malaysia', 'Malaysia', '_Asia', 'MY'),
('Maldives', 'Maldives', '_Asia', 'MV'),
('Mali', 'Mali', '_Africa', 'ML'),
('Malta', 'Malta', '_Europe', 'MT'),
('Marshall Islands', 'Marshall Islands', '_Oceania', 'MH'),
('Mauritania', 'Mauritania', '_Africa', 'MR'),
('Mauritius', 'Mauritius', '_Africa', 'MU'),
('Mayotte', 'Mayotte', '_Africa', 'YT'),
('Mexico', 'Mexico', '_North America', 'MX'),
('Moldova', 'Moldova', '_Europe', 'MD'),
('Monaco', 'Monaco', '_Europe', 'MC'),
('Mongolia', 'Mongolia', '_Asia', 'MN'),
('Montenegro', 'Montenegro', '_Europe', 'ME'),
('Morocco', 'Morocco', '_Africa', 'MA'),
('Mozambique', 'Mozambique', '_Africa', 'MZ'),
('Myanmar', 'Myanmar', '_Asia', 'MM'),
('Namibia', 'Namibia', '_Africa', 'NA'),
('Nauru', 'Nauru', '_Oceania', 'NR'),
('Nepal', 'Nepal', '_Asia', 'NP'),
('Netherlands', 'Netherlands', '_Europe', 'NL'),
('New Caledonia', 'New Caledonia', '_Oceania', 'NC'),
('New Zealand', 'New Zealand', '_Oceania', 'NZ'),
('Nicaragua', 'Nicaragua', '_North America', 'NI'),
('Niger', 'Niger', '_Africa', 'NE'),
('Nigeria', 'Nigeria', '_Africa', 'NG'),
('Niue', 'Niue', '_Oceania', 'NU'),
('North Korea', 'North Korea', '_Asia', 'KP'),
('Norway', 'Norway', '_Europe', 'NO'),
('Oman', 'Oman', '_Asia', 'OM'),
('Pakistan', 'Pakistan', '_Asia', 'PK'),
('Palestine', 'Palestine', '_Asia', 'PS'),
('Panama', 'Panama', '_North America', 'PA'),
('Papua New Guinea', 'Papua New Guinea', '_Oceania', 'PG'),
('Paraguay', 'Paraguay', '_South America', 'PY'),
('Peru', 'Peru', '_South America', 'PE'),
('Philippines', 'Philippines', '_Asia', 'PH'),
('Pitcairn Islands', 'Pitcairn Islands', '_Oceania', 'PN'),
('Poland', 'Poland', '_Europe', 'PL'),
('Portugal', 'Portugal', '_Europe', 'PT'),
('Puerto Rico', 'Puerto Rico', '_North America', 'PR'),
('Qatar', 'Qatar', '_Asia', 'QA'),
('Romania', 'Romania', '_Europe', 'RO'),
('Russia', 'Russia', '_Europe', 'RU'),
('Saint Kitts and Nevis', 'Saint Kitts and Nevis', '_North America', 'KN'),
('Saint Lucia', 'Saint Lucia', '_North America', 'LC'),
('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', '_North America', 'VC'),
('Samoa', 'Samoa', '_Oceania', 'WS'),
('San Marino', 'San Marino', '_Europe', 'SM'),
('Sao Tome and Principe', 'Sao Tome and Principe', '_Africa', 'ST'),
('Saudi Arabia', 'Saudi Arabia', '_Asia', 'SA'),
('Senegal', 'Senegal', '_Africa', 'SN'),
('Serbia', 'Serbia', '_Europe', 'RS'),
('Sierra Leone', 'Sierra Leone', '_Africa', 'SL'),
('Singapore', 'Singapore', '_Asia', 'SG'),
('Slovakia', 'Slovakia', '_Europe', 'SK'),
('Slovenia', 'Slovenia', '_Europe', 'SI'),
('Solomon Islands', 'Solomon Islands', '_Oceania', 'SB'),
('Somalia', 'Somalia', '_Africa', 'SO'),
('South Africa', 'South Africa', '_Africa', 'ZA'),
('South Sudan', 'South Sudan', '_Africa', 'SS'),
('Spain', 'Spain', '_Europe', 'ES'),
('Sri Lanka', 'Sri Lanka', '_Asia', 'LK'),
('Sudan', 'Sudan', '_Africa', 'SD'),
('Suriname', 'Suriname', '_South America', 'SR'),
('Swaziland', 'Swaziland', '_Africa', 'SZ'),
('Sweden', 'Sweden', '_Europe', 'SE'),
('Switzerland', 'Switzerland', '_Europe', 'CH'),
('Syria', 'Syria', '_Asia', 'SY'),
('Taiwan', 'Taiwan', '_Asia', 'TW'),
('Tanzania', 'Tanzania', '_Africa', 'TZ'),
('Thailand', 'Thailand', '_Asia', 'TH'),
('Togo', 'Togo', '_Africa', 'TG'),
('Tonga', 'Tonga', '_Oceania', 'TO'),
('Trinidad and Tobago', 'Trinidad and Tobago', '_North America', 'TT'),
('Tunisia', 'Tunisia', '_Africa', 'TN'),
('Turkey', 'Turkey', '_Europe', 'TR'),
('Turks and Caicos Islands', 'Turks and Caicos Islands', '_North America', 'TC'),
('Tuvalu', 'Tuvalu', '_Oceania', 'TV'),
('Uganda', 'Uganda', '_Africa', 'UG'),
('Ukraine', 'Ukraine', '_Europe', 'UA'),
('United Arab Emirates', 'United Arab Emirates', '_Asia', 'AE'),
('United Kingdom', 'United Kingdom', '_Europe', 'GB'),
('Uruguay', 'Uruguay', '_South America', 'UY'),
('USA', 'USA', '_North America', 'US'),
('Uzbekistan', 'Uzbekistan', '_Asia', 'UZ'),
('Vanuatu', 'Vanuatu', '_Oceania', 'VU'),
('Venezuela', 'Venezuela', '_South America', 'VE'),
('Vietnam', 'Vietnam', '_Asia', 'VN'),
('XA', 'Multiple Countries (Asia)', '_Asia', 'XA'),
('XE', 'Multiple Countries (Europe)', '_Europe', 'XE'),
('XS', 'Multiple Countries (South America)', '_South America', 'XS'),
('Yemen', 'Yemen', '_Asia', 'YE'),
('Zambia', 'Zambia', '_Africa', 'ZM'),
('Zimbabwe', 'Zimbabwe', '_Africa', 'ZW');"
ActiveRecord::Base.connection.execute(sql)
