# frozen_string_literal: true
Round.create(id: '0', rank: 19, name: 'Qualification round', cellName: 'Qualification', final: 0)
Round.create(id: '1', rank: 29, name: 'First round', cellName: 'First', final: 0)
Round.create(id: '2', rank: 50, name: 'Second round', cellName: 'Second', final: 0)
Round.create(id: '3', rank: 79, name: 'Semi Final', cellName: 'Semi Final', final: 0)
Round.create(id: 'b', rank: 39, name: 'B Final', cellName: 'B Final', final: 0)
Round.create(id: 'c', rank: 90, name: 'Combined Final', cellName: 'Combined Final', final: 1)
Round.create(id: 'd', rank: 20, name: 'Combined First round', cellName: 'Combined First', final: 0)
Round.create(id: 'e', rank: 59, name: 'Combined Second round', cellName: 'Combined Second', final: 0)
Round.create(id: 'f', rank: 99, name: 'Final', cellName: 'Final', final: 1)
Round.create(id: 'g', rank: 70, name: 'Combined Third round', cellName: 'Combined Third', final: 0)
Round.create(id: 'h', rank: 10, name: 'Combined qualification', cellName: 'Combined qualification', final: 0)
