# frozen_string_literal: true

Team.create(friendly_id: 'board', email: "board@worldcubeassociation.org")
Team.create(friendly_id: 'wct', email: "communication@worldcubeassociation.org")
Team.create(friendly_id: 'wct_china', email: "communication-china@worldcubeassociation.org")
Team.create(friendly_id: 'wdc', email: "disciplinary@worldcubeassociation.org")
Team.create(friendly_id: 'wec', email: "ethics@worldcubeassociation.org")
Team.create(friendly_id: 'wfc', email: "finance@worldcubeassociation.org")
Team.create(friendly_id: 'wmt', email: "marketing@worldcubeassociation.org")
Team.create(friendly_id: 'wqac', email: "quality@worldcubeassociation.org")
Team.create(friendly_id: 'wrc', email: "regulations@worldcubeassociation.org")
Team.create(friendly_id: 'wrt', email: "results@worldcubeassociation.org")
Team.create(friendly_id: 'wst', email: "software@worldcubeassociation.org")
Team.create(friendly_id: 'wst_admin', email: "software-admin@worldcubeassociation.org")
Team.create(friendly_id: 'banned', email: "disciplinary@worldcubeassociation.org", hidden: true)
Team.create(friendly_id: 'wcat', email: "competitions@worldcubeassociation.org")
Team.create(friendly_id: 'chair')
Team.create(friendly_id: 'executive_director')
Team.create(friendly_id: 'secretary')
Team.create(friendly_id: 'vice_chair')
Team.create(friendly_id: 'wdpc', hidden: true)
Team.create(friendly_id: 'wac', email: "advisory@worldcubeassociation.org")
Team.create(friendly_id: 'probation', hidden: true)
Team.create(friendly_id: 'weat', email: "assistants@worldcubeassociation.org")
Team.create(friendly_id: 'wsot', email: "sports@worldcubeassociation.org")
Team.create(friendly_id: 'wat', email: "archive@worldcubeassociation.org")
