source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'sass-rails'
gem 'uglifier'
gem 'therubyracer'

gem 'sdoc', group: :doc
gem 'dotenv-rails', :require => 'dotenv/rails-now'
gem 'envied'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'bootstrap-sass'
gem 'mail_form'
gem 'simple_form'
gem 'valid_email'
gem "recaptcha", :require => "recaptcha/rails"
gem 'will_paginate'
gem 'bootstrap-will_paginate'
gem 'local_time'
gem 'devise'
gem 'devise-bootstrap-views'
gem 'doorkeeper'
gem 'newrelic_rpm'

gem 'system'
gem 'unicorn'

# Drupal defines some table columns that conflict with ActiveRecord.
# This gem lets us ignore those columns. Eventually we'll migrate this
# problem away.
gem 'ignorable'

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'faker'

  gem 'byebug'
  gem 'sqlite3'
  gem 'web-console'
  gem 'spring'
end

group :development do
  gem 'pre-commit'
end

group :test do
  gem 'guard-rspec'
  gem 'launchy'
  gem 'capybara'
end

group :production do
  gem 'mysql2'
end
