# frozen_string_literal: true
source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'sass-rails'
gem 'uglifier'
gem 'therubyracer'

gem 'sdoc', group: :doc
gem 'dotenv-rails', :require => 'dotenv/rails-now'
gem 'envied'
gem 'seedbank'

gem 'jquery-rails'
gem 'jbuilder'
gem 'bootstrap-sass'
gem 'mail_form'
gem 'simple_form'
gem 'valid_email'
gem 'recaptcha', :require => 'recaptcha/rails'
gem 'kaminari'
gem 'local_time'
gem 'devise'
gem 'devise-bootstrap-views'
gem 'doorkeeper'
gem 'strip_attributes'
gem 'time_will_tell'
gem 'redcarpet', '~> 3.3'
gem 'world-flags', git: 'git://github.com/world-flags/world-flags.git'
gem 'bootstrap-table-rails'
gem 'money-rails'

# Pointing to jfly/carrierwave-crop which has a workaround for
#  https://github.com/brianreavis/selectize.js/issues/953
gem 'selectize-rails', git: "git://github.com/jfly/selectize-rails.git"

gem 'high_voltage'
gem 'carrierwave'

# Pointing to jfly/carrierwave-crop which has a workaround for
#  https://github.com/kirtithorat/carrierwave-crop/issues/17
gem 'carrierwave-crop', git: "git://github.com/jfly/carrierwave-crop.git"

gem 'mini_magick'
gem 'mysql2'
gem 'premailer-rails'
gem 'nokogiri'
gem 'font-awesome-sass'
gem 'lodash-rails'
gem 'cocoon'
gem 'momentjs-rails', '~> 2.9',  :github => 'derekprior/momentjs-rails'
gem 'datetimepicker-rails', github: 'zpaulovics/datetimepicker-rails', branch: 'master', submodules: true
gem 'blocks'
gem 'rack-cors', require: 'rack/cors'
gem 'api-pagination'
gem 'delayed_job_active_record'
gem 'daemons'
gem 'i18n-country-translations'

source 'https://rails-assets.org' do
  gem 'rails-assets-autosize'
  gem 'rails-assets-simplemde'
end

group :development, :test do
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'poltergeist'
  gem 'capybara-screenshot'

  gem 'byebug'
  gem 'web-console'
  gem 'i18n-tasks', '~> 0.9.5'
end

group :development do
  gem 'pre-commit'
  gem 'rubocop', require: false
  gem 'scss_lint', require: false
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'bullet'
end

group :test do
  gem 'rake' # As per http://docs.travis-ci.com/user/languages/ruby/
  gem 'guard-rspec'
  gem 'launchy'
  gem 'capybara'
  gem 'oga' # XML parsing library introduced for testing RSS feed
  gem 'database_cleaner'

  # Rails 4 apparently doesn't run after_commit handlers in tests. We need
  # to test carrierwave's file deletion code, which runs inside of an
  # after_commit callback, so we have this gem to get it to run in tests.
  gem 'test_after_commit'
end

group :production do
  gem 'unicorn'
  gem 'newrelic_rpm'
end
