# frozen_string_literal: true
source 'https://rubygems.org'

# From https://github.com/bundler/bundler/issues/4978#issuecomment-272248627
git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '4.2.7.1'
gem 'rails-i18n', github: 'svenfuchs/rails-i18n', branch: 'rails-4-x'
gem 'sass-rails'
gem 'uglifier'
gem 'therubyracer'

gem 'sdoc', group: :doc
gem 'dotenv-rails', require: 'dotenv/rails-now'
gem 'envied'
gem 'seedbank'

gem 'jquery-rails'
gem 'jbuilder'
gem 'bootstrap-sass'
gem 'mail_form'
gem 'simple_form'
gem 'valid_email'
gem 'recaptcha', require: 'recaptcha/rails'
gem 'kaminari'
gem 'kaminari-i18n'
gem 'devise'
gem 'devise-bootstrap-views'
gem 'doorkeeper'
gem 'doorkeeper-i18n'
gem 'strip_attributes'
gem 'redcarpet'
gem 'world-flags', github: 'world-flags/world-flags'
gem 'bootstrap-table-rails'
gem 'money-rails'

# Pointing to jfly/selectize-rails which has a workaround for
#  https://github.com/selectize/selectize.js/issues/953
gem 'selectize-rails', github: 'jfly/selectize-rails'

gem 'high_voltage'
gem 'carrierwave'

# Pointing to jfly/carrierwave-crop which has a workaround for
#  https://github.com/kirtithorat/carrierwave-crop/issues/17
gem 'carrierwave-crop', github: 'jfly/carrierwave-crop'

gem 'mini_magick'
gem 'mysql2'
gem 'premailer-rails'
gem 'nokogiri'
gem 'font-awesome-sass'
gem 'lodash-rails'
gem 'cocoon'
gem 'momentjs-rails', github: 'derekprior/momentjs-rails'
gem 'datetimepicker-rails', github: 'zpaulovics/datetimepicker-rails', branch: 'master', submodules: true
gem 'blocks'
gem 'rack-cors', require: 'rack/cors'
gem 'api-pagination'
gem 'delayed_job_active_record'
gem 'daemons'
gem 'i18n-country-translations'
gem 'http_accept_language'

source 'https://rails-assets.org' do
  gem 'rails-assets-autosize'

  # simplemde is pinned to 1.10.1 because version 1.11.0 doesn't give us compiled assets.
  # See
  # https://github.com/NextStepWebs/simplemde-markdown-editor/issues/407 and
  # https://github.com/tenex/rails-assets/issues/367.
  gem 'rails-assets-simplemde', '1.10.1'
end

group :development, :test do
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'poltergeist'
  gem 'capybara-screenshot'

  gem 'byebug'
  gem 'i18n-tasks'
  gem 'i18n-spec'
end

group :development do
  gem 'pre-commit'
  gem 'rubocop'
  gem 'scss_lint', require: false
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'bullet'
  gem 'web-console'
end

group :test do
  gem 'rake' # As per http://docs.travis-ci.com/user/languages/ruby/
  gem 'guard-rspec'
  gem 'launchy'
  gem 'capybara'
  gem 'oga' # XML parsing library introduced for testing RSS feed
  gem 'database_cleaner'

  # Rails 4 apparently doesn't run after_commit handlers in tests. We need
  # to test carrierwave's file deletion code, which runs inside of an
  # after_commit callback, so we have this gem to get it to run in tests.
  gem 'test_after_commit'
end

group :production do
  gem 'unicorn'
  gem 'newrelic_rpm'
end
