openapi: 3.1.0
info:
  title: WCA Registration API Documentation
  summary: Documentation of the WCA Registration API, currently in progress
  description: The WCA API allows developers to access data from the WCA using JWT
  contact:
    name: WCA Software Team
    url: https://www.worldcubeassociation.org
    email: software@worldcubeassociation.org
  version: 0.0.1
servers:
  - url: http://localhost:3000/api/v1
    description: The production API server
paths:
  /competitions/{competitionId}/registrations:
    get:
      summary: Get competition registrations
      parameters:
        - name: competitionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RegistrationData'
components:
  schemas:
    RegistrationData:
      type: object
      required:
        - id
        - registrant_id
        - user_id
        - user
        - competing
      properties:
        id:
          type: integer
        registrant_id:
          type: integer
        user_id:
          type: integer
        guests:
          type: integer
        user:
          type: object
          required:
            - id
            - name
            - gender
            - country_iso2
          properties:
            id:
              type: integer
            name:
              type: string
            gender:
              type: string
            country_iso2:
              type: string
        competing:
          type: object
          required:
            - event_ids
          properties:
            event_ids:
              type: array
              items:
                type: string
            # only when authenticated
            registration_status:
              type: string
            registered_on:
              type: string
              format: datetime
            comment:
              type: string
            admin_comment:
              type: string
        # only when authenticated
        payment:
          type: object
          properties:
            has_paid:
              type: boolean
            payment_status:
              type: string
            paid_amount_iso:
              type: integer
            currency_code:
              type: string
            updated_at:
              type: string
              format: datetime
