/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    nav: Nav;
  };
  globalsSelect: {
    nav: NavSelect<false> | NavSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  email: string;
  emailVerified?: string | null;
  name?: string | null;
  image?: string | null;
  accounts?:
    | {
        id?: string | null;
        provider: string;
        providerAccountId: string;
        type: string;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  id?: T;
  email?: T;
  emailVerified?: T;
  name?: T;
  image?: T;
  accounts?:
    | T
    | {
        id?: T;
        provider?: T;
        providerAccountId?: T;
        type?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav".
 */
export interface Nav {
  id: number;
  entry: (
    | {
        title: string;
        displayIcon?:
          | (
              | 'About the Regulations'
              | 'About the WCA'
              | 'Admin Results'
              | 'All Competitions'
              | 'Bookmark'
              | 'Clone'
              | 'Competition Not Started'
              | 'Registration Closed'
              | 'Registration Closed (Red)'
              | 'Registration Full but Open'
              | 'Registration Full but Open (Orange)'
              | 'Registration Not Full, Open'
              | 'Registration Not Full, Open (Green)'
              | 'Registration Not Open Yet'
              | 'Registration Not Open Yet (Grey)'
              | 'Registration Open Date'
              | 'Registration Close Date'
              | 'Competitors'
              | 'Contact'
              | 'Delegate Report'
              | 'Details'
              | 'Developer Export'
              | 'Disciplinary Log'
              | 'Disclaimer'
              | 'Download'
              | 'Edit'
              | 'Educational Resources'
              | 'Error'
              | 'External Link'
              | 'Facebook'
              | 'Filters'
              | 'GitHub'
              | 'Guidelines'
              | 'Help and FAQs'
              | 'Incidents Log'
              | 'Information'
              | 'Instagram'
              | 'Language'
              | 'List'
              | 'Location'
              | 'Manage Tabs'
              | 'Map'
              | 'Media Submission'
              | 'Menu'
              | 'Multimedia'
              | 'My Competitions'
              | 'My Results'
              | 'National Championship'
              | 'New Competition'
              | 'On-the-Spot Registration'
              | 'Payment'
              | 'Privacy'
              | 'Rankings'
              | 'Records'
              | 'Regional Organisations'
              | 'Register'
              | 'Registration'
              | 'Regulations and Guidelines'
              | 'Regulations History'
              | 'Regulations'
              | 'Results Export'
              | 'Scrambles'
              | 'Search'
              | 'Spectators'
              | 'Speedcubing History'
              | 'Spots Left'
              | 'Statistics'
              | 'Teams, Committees and Councils'
              | 'Tools'
              | 'Translators'
              | 'Twitch'
              | 'User'
              | 'Users / Persons'
              | 'Venue'
              | 'WCA Delegates'
              | 'WCA Documents'
              | 'WCA Live'
              | 'WCA Officers and Board'
              | 'Weibo'
              | 'X (formerly Twitter)'
              | 'YouTube'
            )
          | null;
        entries: (
          | {
              displayText: string;
              targetLink: string;
              displayIcon?:
                | (
                    | 'About the Regulations'
                    | 'About the WCA'
                    | 'Admin Results'
                    | 'All Competitions'
                    | 'Bookmark'
                    | 'Clone'
                    | 'Competition Not Started'
                    | 'Registration Closed'
                    | 'Registration Closed (Red)'
                    | 'Registration Full but Open'
                    | 'Registration Full but Open (Orange)'
                    | 'Registration Not Full, Open'
                    | 'Registration Not Full, Open (Green)'
                    | 'Registration Not Open Yet'
                    | 'Registration Not Open Yet (Grey)'
                    | 'Registration Open Date'
                    | 'Registration Close Date'
                    | 'Competitors'
                    | 'Contact'
                    | 'Delegate Report'
                    | 'Details'
                    | 'Developer Export'
                    | 'Disciplinary Log'
                    | 'Disclaimer'
                    | 'Download'
                    | 'Edit'
                    | 'Educational Resources'
                    | 'Error'
                    | 'External Link'
                    | 'Facebook'
                    | 'Filters'
                    | 'GitHub'
                    | 'Guidelines'
                    | 'Help and FAQs'
                    | 'Incidents Log'
                    | 'Information'
                    | 'Instagram'
                    | 'Language'
                    | 'List'
                    | 'Location'
                    | 'Manage Tabs'
                    | 'Map'
                    | 'Media Submission'
                    | 'Menu'
                    | 'Multimedia'
                    | 'My Competitions'
                    | 'My Results'
                    | 'National Championship'
                    | 'New Competition'
                    | 'On-the-Spot Registration'
                    | 'Payment'
                    | 'Privacy'
                    | 'Rankings'
                    | 'Records'
                    | 'Regional Organisations'
                    | 'Register'
                    | 'Registration'
                    | 'Regulations and Guidelines'
                    | 'Regulations History'
                    | 'Regulations'
                    | 'Results Export'
                    | 'Scrambles'
                    | 'Search'
                    | 'Spectators'
                    | 'Speedcubing History'
                    | 'Spots Left'
                    | 'Statistics'
                    | 'Teams, Committees and Councils'
                    | 'Tools'
                    | 'Translators'
                    | 'Twitch'
                    | 'User'
                    | 'Users / Persons'
                    | 'Venue'
                    | 'WCA Delegates'
                    | 'WCA Documents'
                    | 'WCA Live'
                    | 'WCA Officers and Board'
                    | 'Weibo'
                    | 'X (formerly Twitter)'
                    | 'YouTube'
                  )
                | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'LinkItem';
            }
          | {
              title: string;
              displayIcon?:
                | (
                    | 'About the Regulations'
                    | 'About the WCA'
                    | 'Admin Results'
                    | 'All Competitions'
                    | 'Bookmark'
                    | 'Clone'
                    | 'Competition Not Started'
                    | 'Registration Closed'
                    | 'Registration Closed (Red)'
                    | 'Registration Full but Open'
                    | 'Registration Full but Open (Orange)'
                    | 'Registration Not Full, Open'
                    | 'Registration Not Full, Open (Green)'
                    | 'Registration Not Open Yet'
                    | 'Registration Not Open Yet (Grey)'
                    | 'Registration Open Date'
                    | 'Registration Close Date'
                    | 'Competitors'
                    | 'Contact'
                    | 'Delegate Report'
                    | 'Details'
                    | 'Developer Export'
                    | 'Disciplinary Log'
                    | 'Disclaimer'
                    | 'Download'
                    | 'Edit'
                    | 'Educational Resources'
                    | 'Error'
                    | 'External Link'
                    | 'Facebook'
                    | 'Filters'
                    | 'GitHub'
                    | 'Guidelines'
                    | 'Help and FAQs'
                    | 'Incidents Log'
                    | 'Information'
                    | 'Instagram'
                    | 'Language'
                    | 'List'
                    | 'Location'
                    | 'Manage Tabs'
                    | 'Map'
                    | 'Media Submission'
                    | 'Menu'
                    | 'Multimedia'
                    | 'My Competitions'
                    | 'My Results'
                    | 'National Championship'
                    | 'New Competition'
                    | 'On-the-Spot Registration'
                    | 'Payment'
                    | 'Privacy'
                    | 'Rankings'
                    | 'Records'
                    | 'Regional Organisations'
                    | 'Register'
                    | 'Registration'
                    | 'Regulations and Guidelines'
                    | 'Regulations History'
                    | 'Regulations'
                    | 'Results Export'
                    | 'Scrambles'
                    | 'Search'
                    | 'Spectators'
                    | 'Speedcubing History'
                    | 'Spots Left'
                    | 'Statistics'
                    | 'Teams, Committees and Councils'
                    | 'Tools'
                    | 'Translators'
                    | 'Twitch'
                    | 'User'
                    | 'Users / Persons'
                    | 'Venue'
                    | 'WCA Delegates'
                    | 'WCA Documents'
                    | 'WCA Live'
                    | 'WCA Officers and Board'
                    | 'Weibo'
                    | 'X (formerly Twitter)'
                    | 'YouTube'
                  )
                | null;
              entries: {
                displayText: string;
                targetLink: string;
                displayIcon?:
                  | (
                      | 'About the Regulations'
                      | 'About the WCA'
                      | 'Admin Results'
                      | 'All Competitions'
                      | 'Bookmark'
                      | 'Clone'
                      | 'Competition Not Started'
                      | 'Registration Closed'
                      | 'Registration Closed (Red)'
                      | 'Registration Full but Open'
                      | 'Registration Full but Open (Orange)'
                      | 'Registration Not Full, Open'
                      | 'Registration Not Full, Open (Green)'
                      | 'Registration Not Open Yet'
                      | 'Registration Not Open Yet (Grey)'
                      | 'Registration Open Date'
                      | 'Registration Close Date'
                      | 'Competitors'
                      | 'Contact'
                      | 'Delegate Report'
                      | 'Details'
                      | 'Developer Export'
                      | 'Disciplinary Log'
                      | 'Disclaimer'
                      | 'Download'
                      | 'Edit'
                      | 'Educational Resources'
                      | 'Error'
                      | 'External Link'
                      | 'Facebook'
                      | 'Filters'
                      | 'GitHub'
                      | 'Guidelines'
                      | 'Help and FAQs'
                      | 'Incidents Log'
                      | 'Information'
                      | 'Instagram'
                      | 'Language'
                      | 'List'
                      | 'Location'
                      | 'Manage Tabs'
                      | 'Map'
                      | 'Media Submission'
                      | 'Menu'
                      | 'Multimedia'
                      | 'My Competitions'
                      | 'My Results'
                      | 'National Championship'
                      | 'New Competition'
                      | 'On-the-Spot Registration'
                      | 'Payment'
                      | 'Privacy'
                      | 'Rankings'
                      | 'Records'
                      | 'Regional Organisations'
                      | 'Register'
                      | 'Registration'
                      | 'Regulations and Guidelines'
                      | 'Regulations History'
                      | 'Regulations'
                      | 'Results Export'
                      | 'Scrambles'
                      | 'Search'
                      | 'Spectators'
                      | 'Speedcubing History'
                      | 'Spots Left'
                      | 'Statistics'
                      | 'Teams, Committees and Councils'
                      | 'Tools'
                      | 'Translators'
                      | 'Twitch'
                      | 'User'
                      | 'Users / Persons'
                      | 'Venue'
                      | 'WCA Delegates'
                      | 'WCA Documents'
                      | 'WCA Live'
                      | 'WCA Officers and Board'
                      | 'Weibo'
                      | 'X (formerly Twitter)'
                      | 'YouTube'
                    )
                  | null;
                id?: string | null;
                blockName?: string | null;
                blockType: 'LinkItem';
              }[];
              id?: string | null;
              blockName?: string | null;
              blockType: 'NestedDropdown';
            }
          | {
              id?: string | null;
              blockName?: string | null;
              blockType: 'VisualDivider';
            }
        )[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'NavDropdown';
      }
    | {
        displayText: string;
        targetLink: string;
        displayIcon?:
          | (
              | 'About the Regulations'
              | 'About the WCA'
              | 'Admin Results'
              | 'All Competitions'
              | 'Bookmark'
              | 'Clone'
              | 'Competition Not Started'
              | 'Registration Closed'
              | 'Registration Closed (Red)'
              | 'Registration Full but Open'
              | 'Registration Full but Open (Orange)'
              | 'Registration Not Full, Open'
              | 'Registration Not Full, Open (Green)'
              | 'Registration Not Open Yet'
              | 'Registration Not Open Yet (Grey)'
              | 'Registration Open Date'
              | 'Registration Close Date'
              | 'Competitors'
              | 'Contact'
              | 'Delegate Report'
              | 'Details'
              | 'Developer Export'
              | 'Disciplinary Log'
              | 'Disclaimer'
              | 'Download'
              | 'Edit'
              | 'Educational Resources'
              | 'Error'
              | 'External Link'
              | 'Facebook'
              | 'Filters'
              | 'GitHub'
              | 'Guidelines'
              | 'Help and FAQs'
              | 'Incidents Log'
              | 'Information'
              | 'Instagram'
              | 'Language'
              | 'List'
              | 'Location'
              | 'Manage Tabs'
              | 'Map'
              | 'Media Submission'
              | 'Menu'
              | 'Multimedia'
              | 'My Competitions'
              | 'My Results'
              | 'National Championship'
              | 'New Competition'
              | 'On-the-Spot Registration'
              | 'Payment'
              | 'Privacy'
              | 'Rankings'
              | 'Records'
              | 'Regional Organisations'
              | 'Register'
              | 'Registration'
              | 'Regulations and Guidelines'
              | 'Regulations History'
              | 'Regulations'
              | 'Results Export'
              | 'Scrambles'
              | 'Search'
              | 'Spectators'
              | 'Speedcubing History'
              | 'Spots Left'
              | 'Statistics'
              | 'Teams, Committees and Councils'
              | 'Tools'
              | 'Translators'
              | 'Twitch'
              | 'User'
              | 'Users / Persons'
              | 'Venue'
              | 'WCA Delegates'
              | 'WCA Documents'
              | 'WCA Live'
              | 'WCA Officers and Board'
              | 'Weibo'
              | 'X (formerly Twitter)'
              | 'YouTube'
            )
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'LinkItem';
      }
  )[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav_select".
 */
export interface NavSelect<T extends boolean = true> {
  entry?:
    | T
    | {
        NavDropdown?:
          | T
          | {
              title?: T;
              displayIcon?: T;
              entries?:
                | T
                | {
                    LinkItem?:
                      | T
                      | {
                          displayText?: T;
                          targetLink?: T;
                          displayIcon?: T;
                          id?: T;
                          blockName?: T;
                        };
                    NestedDropdown?:
                      | T
                      | {
                          title?: T;
                          displayIcon?: T;
                          entries?:
                            | T
                            | {
                                LinkItem?:
                                  | T
                                  | {
                                      displayText?: T;
                                      targetLink?: T;
                                      displayIcon?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                              };
                          id?: T;
                          blockName?: T;
                        };
                    VisualDivider?:
                      | T
                      | {
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        LinkItem?:
          | T
          | {
              displayText?: T;
              targetLink?: T;
              displayIcon?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}