FROM phpmyadmin/phpmyadmin:5.2

# Add custom entrypoint script to the image
COPY load-ca-and-start.sh /custom-entrypoint.sh
RUN cp -r /var/www/html /var/www/phpmyadmin && mkdir -p /var/www/html/results && mv /var/www/phpmyadmin /var/www/html/results/database

# Make the custom entrypoint script executable
RUN chmod +x /custom-entrypoint.sh

# Set custom entrypoint script as the entrypoint
ENTRYPOINT ["/custom-entrypoint.sh"]
CMD ["apache2-foreground"]
