development:
  adapter: anycable
  url: <%= EnvConfig.ANYCABLE_REDIS_URL %>

test:
  adapter: test

production:
  adapter: <%= EnvConfig.WCA_LIVE_SITE? ? "redis" : "anycable" %>
  url: <%= EnvConfig.ANYCABLE_REDIS_URL %>
