development:
  adapter: anycable
  url: <%= EnvConfig.ANYCABLE_REDIS_URL %>

test:
  adapter: test

production:
  adapter: <%= Live::Config.enabled? ? "anycable" : "redis" %>
  url: <%= EnvConfig.ANYCABLE_REDIS_URL %>
