# Split context in several files.
#
# By default only one file with all translations is exported and
# no configuration is required. Your settings for asset pipeline
# are automatically recognized.
#
# If you want to split translations into several files or specify
# locale contexts that will be exported, just use this file to do
# so.
#
# For more informations about the export options with this file, please
# refer to the README
#
#
# If you're going to use the Rails 3.1 asset pipeline, change
# the following configuration to something like this:
#
# translations:
#   - file: "app/assets/javascripts/i18n/translations.js"
#
# If you're running an old version, you can use something
# like this:
#
# translations:
#   - file: "app/assets/javascripts/i18n/translations.js"
#     only: "*"
#

# This sets which keys we export from the locale file!
# It will need to be updated as we port more and more stuff to React.
translations:
  # Using the `:locale` template in the filename here automagically makes i18n-js iterate over the available languages.
  - file: "app/webpacker/rails_translations/:locale.json"
    patterns:
      - "*.about.*"
      - "*.activerecord.attributes.user.*"
      - "*.common.*"
      - "*.competitions.*"
      - "*.countries.*"
      - "*.continents.*"
      - "*.delegates_page.*"
      - "*.enums.*"
      - "*.events.*"
      - "*.formats.*"
      - "*.incidents_log.*"
      - "*.logo.*"
      - "*.qualification.*"
      - "*.regional_organizations.*"
      - "*.round.*"
      - "*.search_results.*"
      - "*.continents.*"
      - "*.layouts.*"
      - "*.user_roles.*"
      - "*.user_groups.*"
      - "*.simple_form.hints.competition.*"
      - "*.simple_form.options.competition.*"
      - "*.simple_form.options.registration.status.*"
      - "*.activerecord.attributes.competition.*"
      - "*.activerecord.attributes.competition_series.*"
      - "*.activerecord.attributes.championship.*"
      - "*.activerecord.attributes.registration.*"
      - "*.datetime.*"
      - "*.wca.errors.messages.form_error"
      - "*.page.*"
      - "*.registrations.*"
      - "*.api.*"
      - "*.cutoff.*"
      - "*.advancement_condition.*"
      - "*.rounds.*"
      - "*.attempts.*"
      - "*.time_limit.*"
