openapi: 3.1.0
info:
  title: WCA API Documentation
  summary: Documentation of the WCA API, currently in progress
  description: The WCA API allows developers to access data from the WCA using oidc
  contact:
    name: WCA Software Team
    url: https://www.worldcubeassociation.org
    email: software@worldcubeassociation.org
  version: 0.1.0
servers:
  - url: http://localhost:3000/api/v0
    description: The production API server
paths:
  /competitions/{competitionId}/:
    $ref: 'paths/competitions/competitionById.yaml'
  /competitions/{competitionId}/events:
    $ref: 'paths/competitions/competitionEvents.yaml'
  /competitions/{competitionId}/schedule:
    $ref: 'paths/competitions/competitionSchedule.yaml'
  /competitions/{competitionId}/registrations:
    $ref: 'paths/competitions/competitionRegistrations.yaml'
  /competitions/{competitionId}/podiums:
    $ref: 'paths/competitions/competitionPodiums.yaml'
  /competition_index:
    $ref: 'paths/competitions/competitionList.yaml'

  /incidents:
    $ref: 'paths/regulations/incidentsList.yaml'

  /persons/{wca_id}/:
    $ref: 'paths/users/personByWCAId.yaml'
  /persons/{wca_id}/results:
    $ref: 'paths/users/personResults.yaml'

  /user_groups:
    $ref: 'paths/users/userGroups.yaml'
  /user_roles:
    $ref: 'paths/users/userRoles.yaml'
  /users/me/permissions:
    $ref: 'paths/users/userPermissions.yaml'

  /regulations/translations:
    $ref: 'paths/regulations/regulationTranslations.yaml'

  /export/public:
    $ref: 'paths/results/publicExports.yaml'

  /known-timezones:
    $ref: 'paths/wca/knownTimezones.yaml'

  /regional-organizations:
    $ref: 'paths/wca/regionalOrganizations.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
