import createClient from "openapi-fetch";
import type {
  ClientPathsWithMethod,
  FetchResponse,
  MaybeOptionalInit,
} from "openapi-fetch";
import type { paths } from "@/types/openapi"; // generated by openapi-typescript
import { type ErrorDetails, toErrorDetails } from "@/lib/wca/errorDetails";

export const serverClient = createClient<paths>({
  baseUrl: process.env.WCA_BACKEND_API_URL,
  headers: { "Content-Type": "application/json" },
});
export const serverClientWithToken = (token: string) =>
  createClient<paths>({
    baseUrl: process.env.WCA_BACKEND_API_URL,
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
  });

export const unauthenticatedClient = createClient<paths>({
  baseUrl: process.env.NEXT_PUBLIC_WCA_FRONTEND_API_URL,
  headers: { "Content-Type": "application/json" },
});
export const authenticatedClient = (token: string) =>
  createClient<paths>({
    baseUrl: process.env.NEXT_PUBLIC_WCA_FRONTEND_API_URL,
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
  });

/** Distributes over the `data`/`error` union so the result still narrows. */
type Serializable<T> = T extends { response: Response }
  ? Omit<T, "response"> & { response: ErrorDetails }
  : never;

/**
 * `serverClient` for use inside a `"use cache"` function: `Response` is a host
 * object with a single-use stream body, so it cannot be serialized across the
 * cache boundary. This swaps it for the plain `ErrorDetails` that `OpenapiError`
 * renders, so no individual fetcher has to remember to.
 */
export const cachedServerClient = {
  GET: async <
    Path extends ClientPathsWithMethod<typeof serverClient, "get">,
    Init extends MaybeOptionalInit<paths[Path], "get">,
  >(
    url: Path,
    ...init: [Init] | []
  ) => {
    const { response, ...result } = await serverClient.GET(
      url,
      ...(init as [Init & { [key: string]: unknown }]),
    );

    return { ...result, response: toErrorDetails(response) } as Serializable<
      FetchResponse<paths[Path]["get"], Init, `application/json`>
    >;
  },
};
