import createClient from "openapi-fetch";
import type { paths } from "./wcaSchema"; // generated by openapi-typescript

export const unauthenticatedClient = createClient<paths>({ baseUrl: "http://localhost:3000/api/v0/" });
export const authenticatedClient = (token: string) => createClient<paths>({ baseUrl: "http://localhost:3000/api/v0/", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` } });
