default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  host: <%= EnvConfig.DATABASE_HOST %>
  port: 3306
  username: root
  password: <%= AppSecrets.DATABASE_PASSWORD %>

production:
  primary:
    <<: *default
    database: cubing
  primary_replica:
    <<: *default
    database: cubing
    host: <%= EnvConfig.READ_REPLICA_HOST %>
    replica: true
  developer_dump:
    <<: *default
    database: developer_dump
    database_tasks: false
  results_dump:
    <<: *default
    database: results_dump
    database_tasks: false
    migrations_paths: db/results_migrate

development:
  primary:
    <<: *default
    database: wca_development
  primary_replica:
    <<: *default
    database: wca_development
    replica: true
  developer_dump:
    <<: *default
    database: wca_dump_developer
  results_dump:
    <<: *default
    database: wca_dump_results
    migrations_paths: db/results_migrate

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  primary:
    <<: *default
    database: wca_test
  primary_replica:
    <<: *default
    database: wca_test
    replica: true
  # These two can have identical names to the config for normal development mode,
  # because they are only temporary dump tables anyways that get dropped after every run.
  developer_dump:
    <<: *default
    database: wca_dump_developer
    database_tasks: false
  results_dump:
    <<: *default
    database: wca_dump_results
    database_tasks: false
    migrations_paths: db/results_migrate
