type: object
properties:
  key:
    type: string
  is_editable:
    type: boolean
  is_post_step:
    type: boolean
  parameters:
    type: object
  summary_status:
    type: string
    enum:
      - show
      - hide
      - priority
required:
  - key
  - is_editable
  - is_post_step
  - summary_status
