import React, { useCallback } from 'react';
import {
  Accordion, Breadcrumb, Button, Header, Icon, Popup, Table,
} from 'semantic-ui-react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import _ from 'lodash';
import { fetchJsonOrError } from '../../lib/requests/fetchWithAuthenticityToken';
import { scrambleFileUrl } from '../../lib/requests/routes.js.erb';
import Loading from '../Requests/Loading';
import { prefixForIndex, roundToRoundTypeName, searchRecursive } from './util';
import { events } from '../../lib/wca-data.js.erb';
import { getFullDateTimeString } from '../../lib/utils/dates';
import { useMoveScrambleSetModal } from './MoveScrambleSetModal';

async function deleteScrambleFile({ fileId }) {
  const { data } = await fetchJsonOrError(scrambleFileUrl(fileId), {
    method: 'DELETE',
  });

  return data;
}

export function ExternalSetActionButtons({
  scrSet,
  rootMatchState,
  dispatchMatchState,
  fluid = true,
}) {
  const moveScramble = useMoveScrambleSetModal();

  const autoInsertNavigation = searchRecursive(
    rootMatchState,
    ['events', 'rounds'],
    scrSet.automatch_wcif_id,
  );

  const dispatchAddExternal = (externalScrambleSet, eventId, roundId) => dispatchMatchState({
    type: 'addExternalToMatching',
    eventId,
    roundId,
    externalScrambleSet,
  });

  const onClickAutoAssign = (eventId, roundId) => dispatchAddExternal(scrSet, eventId, roundId);

  const onClickManualAssign = () => moveScramble(
    scrSet,
    scrSet.event_id,
    scrSet.automatch_wcif_id,
  ).then(({ addedScrSet, eventId, roundId }) => dispatchAddExternal(addedScrSet, eventId, roundId));

  return (
    <Button.Group compact fluid={fluid}>
      {autoInsertNavigation && (
        <Button
          positive
          basic
          icon="magic"
          content="Auto-Assign"
          onClick={() => onClickAutoAssign(
            autoInsertNavigation.events.id,
            autoInsertNavigation.rounds.id,
          )}
        />
      )}
      <Button
        primary
        basic
        icon="pencil"
        content="Manual"
        onClick={onClickManualAssign}
      />
    </Button.Group>
  );
}

function ScrambleFileHeader({ scrambleFile }) {
  return (
    <>
      {scrambleFile.original_filename}
      <Header.Subheader>
        Generated by
        {' '}
        {scrambleFile.scramble_program}
        <br />
        On
        {' '}
        {getFullDateTimeString(scrambleFile.generated_at)}
      </Header.Subheader>
    </>
  );
}

function FileTableGroupCell({
  fileSets,
  referenceSet,
  filterHierarchy,
  filterIndex,
  children,
}) {
  const filterPrefix = filterHierarchy.slice(0, filterIndex + 1);
  const filterChildren = filterHierarchy.slice(filterIndex + 1);

  const candidateRows = fileSets.filter(
    (set) => filterPrefix.every(
      (key) => set[key] === referenceSet[key],
    ),
  );

  const isPrimaryCell = filterChildren.every((key) => referenceSet[key] === 1);

  if (!isPrimaryCell) {
    return null;
  }

  return (
    <Table.Cell
      textAlign="center"
      verticalAlign="middle"
      singleLine
      rowSpan={candidateRows.length}
    >
      {children}
    </Table.Cell>
  );
}

function ScrambleFileBody({
  scrambleFile,
  matchState,
  dispatchMatchState,
}) {
  const queryClient = useQueryClient();

  const { mutate: deleteMutation, isPending: isDeleting } = useMutation({
    mutationFn: deleteScrambleFile,
    onSuccess: (data) => {
      queryClient.setQueryData(
        ['scramble-files', data.competition_id],
        (prev) => prev.filter((scrFile) => scrFile.id !== data.id),
      );

      dispatchMatchState({ type: 'removeScrambleFile', scrambleFile: data });
    },
  });

  const deleteAction = useCallback(
    () => deleteMutation({ fileId: scrambleFile.id }),
    [deleteMutation, scrambleFile.id],
  );

  const unlinkAction = useCallback(
    () => dispatchMatchState({
      type: 'resetScrambleFile',
      scrambleFile,
    }),
    [dispatchMatchState, scrambleFile],
  );

  const clearAction = (eventId, roundId, sourceIndex) => dispatchMatchState({
    type: 'removeFromMatching',
    eventId,
    roundId,
    sourceIndex,
  });

  const orderedScrambleSets = _.sortBy(scrambleFile.external_scramble_sets, [
    (scrSet) => events.byId[scrSet.event_id].rank,
    'round_number',
    'scramble_set_number',
  ]);

  return (
    <>
      <Table celled structured compact>
        <Table.Header>
          <Table.Row textAlign="center" verticalAlign="middle">
            <Table.HeaderCell collapsing>Event</Table.HeaderCell>
            <Table.HeaderCell collapsing>Round</Table.HeaderCell>
            <Table.HeaderCell collapsing>Scramble Set</Table.HeaderCell>
            <Table.HeaderCell collapsing>Scramble</Table.HeaderCell>
            <Table.HeaderCell>Current Status</Table.HeaderCell>
          </Table.Row>
        </Table.Header>
        <Table.Body>
          {orderedScrambleSets.map((scrSet, idx, allSets) => {
            const actualNavigation = searchRecursive(
              matchState,
              ['events', 'rounds', 'external_scramble_sets'],
              scrSet.id,
            );

            return (
              <Table.Row key={scrSet.id}>
                <FileTableGroupCell
                  fileSets={allSets}
                  referenceSet={scrSet}
                  filterHierarchy={['event_id', 'round_number', 'scramble_set_number']}
                  filterIndex={0}
                >
                  <Popup
                    content={events.byId[scrSet.event_id].name}
                    trigger={<Icon size="large" className={`cubing-icon event-${scrSet.event_id}`} />}
                    position="top center"
                  />
                </FileTableGroupCell>
                <FileTableGroupCell
                  fileSets={allSets}
                  referenceSet={scrSet}
                  filterHierarchy={['event_id', 'round_number', 'scramble_set_number']}
                  filterIndex={1}
                >
                  {scrSet.round_number}
                </FileTableGroupCell>
                <FileTableGroupCell
                  fileSets={allSets}
                  referenceSet={scrSet}
                  filterHierarchy={['event_id', 'round_number', 'scramble_set_number']}
                  filterIndex={2}
                >
                  {prefixForIndex(scrSet.scramble_set_number - 1)}
                </FileTableGroupCell>
                <Table.Cell
                  textAlign="center"
                  verticalAlign="middle"
                  colSpan={2}
                >
                  {actualNavigation ? (
                    <>
                      <Breadcrumb size="tiny">
                        <Breadcrumb.Section>
                          <Icon className={`cubing-icon event-${actualNavigation.events.id}`} />
                        </Breadcrumb.Section>
                        <Breadcrumb.Divider icon="chevron right" />
                        <Breadcrumb.Section>
                          {roundToRoundTypeName(
                            actualNavigation.rounds.item,
                            actualNavigation.events.item,
                          )}
                        </Breadcrumb.Section>
                        <Breadcrumb.Divider icon="chevron right" />
                        <Breadcrumb.Section>
                          Group
                          {' '}
                          {actualNavigation.external_scramble_sets.index + 1}
                        </Breadcrumb.Section>
                      </Breadcrumb>
                      <Button
                        secondary
                        compact
                        basic
                        icon="unlink"
                        content="Clear"
                        size="tiny"
                        attached="right"
                        onClick={() => clearAction(
                          actualNavigation.events.id,
                          actualNavigation.rounds.id,
                          actualNavigation.external_scramble_sets.index,
                        )}
                      />
                    </>
                  ) : (
                    <ExternalSetActionButtons
                      scrSet={scrSet}
                      rootMatchState={matchState}
                      dispatchMatchState={dispatchMatchState}
                      fluid={false}
                    />
                  )}
                </Table.Cell>
              </Table.Row>
            );
          })}
        </Table.Body>
      </Table>
      <Button.Group widths={2}>
        <Button
          secondary
          icon="unlink"
          content="Clear Assignments"
          onClick={unlinkAction}
        />
        <Button
          negative
          icon="trash"
          content="Delete Upload"
          onClick={deleteAction}
          disabled={isDeleting}
          loading={isDeleting}
        />
      </Button.Group>
    </>
  );
}

export default function ScrambleFileList({
  scrambleFiles,
  isFetching,
  matchState,
  dispatchMatchState,
}) {
  if (isFetching) {
    return <Loading />;
  }

  const panels = scrambleFiles.map((scrFile) => ({
    key: scrFile.id,
    title: {
      as: Header,
      content: <ScrambleFileHeader scrambleFile={scrFile} />,
    },
    content: {
      content: <ScrambleFileBody
        scrambleFile={scrFile}
        matchState={matchState}
        dispatchMatchState={dispatchMatchState}
      />,
    },
  }));

  return (
    <Accordion styled fluid panels={panels} />
  );
}
