import React, { useCallback } from 'react';
import {
  Accordion, Breadcrumb, Button, Header, Icon, Popup, Table,
} from 'semantic-ui-react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import _ from 'lodash';
import { fetchJsonOrError } from '../../lib/requests/fetchWithAuthenticityToken';
import { scrambleFileUrl } from '../../lib/requests/routes.js.erb';
import Loading from '../Requests/Loading';
import {
  ATTEMPTS_UNPACKING_MARKER,
  autoMatchSearch,
  getAttemptsMultiplier,
  prefixForIndex,
  roundToRoundTypeName,
  searchRecursive,
  unpackScrambleSets,
} from './util';
import { events } from '../../lib/wca-data.js.erb';
import { getFullDateTimeString } from '../../lib/utils/dates';
import { useMoveScrambleSetModal } from './MoveScrambleSetModal';

async function deleteScrambleFile({ fileId }) {
  const { data } = await fetchJsonOrError(scrambleFileUrl(fileId), {
    method: 'DELETE',
  });

  return data;
}

function computeAttemptIndex(searchResult) {
  return searchResult.external_scramble_sets.index
    * getAttemptsMultiplier(searchResult.rounds.item)
    + searchResult.external_scrambles.index;
}

function MatchedSetActionButtons({
  matchedNavigation,
  dispatchMatchState,
  isAttemptMode = false,
}) {
  const onClickUnassign = (eventId, roundId, sourceIndex) => dispatchMatchState({
    type: 'removeFromMatching',
    eventId,
    roundId,
    sourceIndex,
    isAttemptMode,
  });

  const unassignIndex = isAttemptMode
    ? computeAttemptIndex(matchedNavigation)
    : matchedNavigation.external_scramble_sets.index;

  return (
    <Button.Group compact>
      <Button
        primary
        basic
        icon="arrows horizontal alternate"
        content="Move"
      />
      <Button
        secondary
        basic
        icon="unlink"
        content="Unassign"
        onClick={() => onClickUnassign(
          matchedNavigation.events.id,
          matchedNavigation.rounds.id,
          unassignIndex,
        )}
      />
    </Button.Group>
  );
}

function calculateBestIndex(scrSet, round) {
  const isAttemptMode = scrSet[ATTEMPTS_UNPACKING_MARKER];
  const setIndex = scrSet.scramble_set_number - 1;

  if (isAttemptMode) {
    const attemptCount = getAttemptsMultiplier(round);

    const extraOffset = scrSet.is_extra ? attemptCount : 0;
    return setIndex * attemptCount + scrSet.scramble_number + extraOffset - 1;
  }

  return scrSet.scramble_set_number - 1;
}

export function ExternalSetActionButtons({
  scrSet,
  autoMatchSettings,
  rootMatchState,
  dispatchMatchState,
  overrideEventId = scrSet.event_id,
  overrideRoundId = scrSet.automatch_wcif_id,
  fluid = true,
}) {
  const moveScramble = useMoveScrambleSetModal();

  const autoInsertNavigation = autoMatchSearch(
    scrSet,
    rootMatchState,
    autoMatchSettings,
  );

  const onClickAutoAssign = (event, round) => {
    const bestIndex = calculateBestIndex(scrSet, round);
    const destinationIndex = autoMatchSettings.tryBestInsert ? bestIndex : undefined;

    return dispatchMatchState({
      type: 'addExternalToMatching',
      eventId: event.id,
      roundId: round.id,
      externalScrambleSet: scrSet,
      destinationIndex,
    });
  };

  const onClickManualAssign = () => moveScramble(
    scrSet,
    overrideEventId,
    overrideRoundId,
  ).then(({ addedScrSet, eventId, roundId }) => dispatchMatchState({
    type: 'addExternalToMatching',
    eventId,
    roundId,
    externalScrambleSet: addedScrSet,
  }));

  return (
    <Button.Group compact fluid={fluid}>
      {autoInsertNavigation && (
        <Button
          positive
          basic
          icon="magic"
          content="Auto-Assign"
          onClick={() => onClickAutoAssign(
            autoInsertNavigation.events.item,
            autoInsertNavigation.rounds.item,
          )}
        />
      )}
      <Button
        primary
        basic
        icon="arrows horizontal alternate"
        content="Move"
        onClick={onClickManualAssign}
      />
    </Button.Group>
  );
}

function ScrambleFileHeader({ scrambleFile }) {
  return (
    <>
      {scrambleFile.original_filename}
      <Header.Subheader>
        Generated by
        {' '}
        {scrambleFile.scramble_program}
        <br />
        On
        {' '}
        {getFullDateTimeString(scrambleFile.generated_at)}
      </Header.Subheader>
    </>
  );
}

function FileTableGroupCell({
  fileSets,
  referenceSet,
  rowSpanCols,
  leadIndexCols = [],
  overrideColSpan = 1,
  children,
}) {
  const setsCoveredBySpan = fileSets.filter(
    (set) => rowSpanCols.every(
      (key) => set[key] === referenceSet[key],
    ),
  );

  const isPrimaryCell = leadIndexCols.every((key) => referenceSet[key] === 1);

  if (!isPrimaryCell) {
    return null;
  }

  return (
    <Table.Cell
      textAlign="center"
      verticalAlign="middle"
      singleLine
      rowSpan={setsCoveredBySpan.length}
      colSpan={overrideColSpan}
    >
      {children}
    </Table.Cell>
  );
}

function ScrambleFileBody({
  scrambleFile,
  autoMatchSettings,
  matchState,
  dispatchMatchState,
}) {
  const queryClient = useQueryClient();

  const { mutate: deleteMutation, isPending: isDeleting } = useMutation({
    mutationFn: deleteScrambleFile,
    onSuccess: (data) => {
      queryClient.setQueryData(
        ['scramble-files', data.competition_id],
        (prev) => prev.filter((scrFile) => scrFile.id !== data.id),
      );

      dispatchMatchState({ type: 'removeScrambleFile', scrambleFile: data });
    },
  });

  const deleteAction = useCallback(
    () => deleteMutation({ fileId: scrambleFile.id }),
    [deleteMutation, scrambleFile.id],
  );

  const clearAllAction = useCallback(
    () => dispatchMatchState({
      type: 'resetScrambleFile',
      scrambleFile,
    }),
    [dispatchMatchState, scrambleFile],
  );

  const currentFileSets = unpackScrambleSets(
    scrambleFile.external_scramble_sets,
    autoMatchSettings,
  );

  const orderedScrambleSets = _.sortBy(currentFileSets, [
    (scrSet) => events.byId[scrSet.event_id].rank,
    'round_number',
    'scramble_set_number',
    'scramble_number',
  ]);

  const autoAssignAction = useCallback(() => dispatchMatchState({
    type: 'autoMatchScrambleSets',
    scrambleSets: orderedScrambleSets,
    settings: autoMatchSettings,
  }), [dispatchMatchState, orderedScrambleSets, autoMatchSettings]);

  return (
    <>
      <Table celled structured compact>
        <Table.Header>
          <Table.Row textAlign="center" verticalAlign="middle">
            <Table.HeaderCell collapsing>Event</Table.HeaderCell>
            <Table.HeaderCell collapsing>Round</Table.HeaderCell>
            <Table.HeaderCell collapsing>Scramble Set</Table.HeaderCell>
            <Table.HeaderCell collapsing>Scramble</Table.HeaderCell>
            <Table.HeaderCell>Current Status</Table.HeaderCell>
            <Table.HeaderCell>Actions</Table.HeaderCell>
          </Table.Row>
        </Table.Header>
        <Table.Body>
          {orderedScrambleSets.map((scrSet, idx, allSets) => {
            const isAttemptMappedScramble = scrSet[ATTEMPTS_UNPACKING_MARKER];
            const stateSearchSuffix = isAttemptMappedScramble ? ['external_scrambles'] : [];

            const actualNavigation = searchRecursive(
              matchState,
              ['events', 'rounds', 'external_scramble_sets', ...stateSearchSuffix],
              scrSet.id,
            );

            const indexColumnSuffix = isAttemptMappedScramble ? ['scramble_number'] : [];

            return (
              <Table.Row key={scrSet.id}>
                <FileTableGroupCell
                  fileSets={allSets}
                  referenceSet={scrSet}
                  rowSpanCols={['event_id']}
                  leadIndexCols={['round_number', 'scramble_set_number', ...indexColumnSuffix]}
                >
                  <Popup
                    content={events.byId[scrSet.event_id].name}
                    trigger={<Icon size="large" className={`cubing-icon event-${scrSet.event_id}`} />}
                    position="top center"
                  />
                </FileTableGroupCell>
                <FileTableGroupCell
                  fileSets={allSets}
                  referenceSet={scrSet}
                  rowSpanCols={['event_id', 'round_number']}
                  leadIndexCols={['scramble_set_number', ...indexColumnSuffix]}
                >
                  {scrSet.round_number}
                </FileTableGroupCell>
                <FileTableGroupCell
                  fileSets={allSets}
                  referenceSet={scrSet}
                  rowSpanCols={['event_id', 'round_number', 'scramble_set_number']}
                  leadIndexCols={indexColumnSuffix}
                  overrideColSpan={2 - indexColumnSuffix.length}
                >
                  {prefixForIndex(scrSet.scramble_set_number - 1)}
                </FileTableGroupCell>
                {indexColumnSuffix.length > 0 && (
                  <FileTableGroupCell
                    fileSets={allSets}
                    referenceSet={scrSet}
                    rowSpanCols={['event_id', 'round_number', 'scramble_set_number', ...indexColumnSuffix]}
                  >
                    {scrSet.scramble_number}
                  </FileTableGroupCell>
                )}
                <Table.Cell
                  textAlign="center"
                  verticalAlign="middle"
                  disabled={!actualNavigation}
                >
                  {actualNavigation ? (
                    <Breadcrumb size="tiny">
                      <Breadcrumb.Section>
                        <Icon className={`cubing-icon event-${actualNavigation.events.id}`} />
                      </Breadcrumb.Section>
                      <Breadcrumb.Divider icon="chevron right" />
                      <Breadcrumb.Section>
                        {roundToRoundTypeName(
                          actualNavigation.rounds.item,
                          actualNavigation.events.item,
                        )}
                      </Breadcrumb.Section>
                      <Breadcrumb.Divider icon="chevron right" />
                      <Breadcrumb.Section>
                        Group
                        {' '}
                        {actualNavigation.external_scramble_sets.index + 1}
                      </Breadcrumb.Section>
                      {isAttemptMappedScramble && (
                      <>
                        <Breadcrumb.Divider icon="chevron right" />
                        <Breadcrumb.Section>
                          Attempt
                          {' '}
                          {actualNavigation.external_scrambles.index + 1}
                        </Breadcrumb.Section>
                      </>
                      )}
                    </Breadcrumb>
                  ) : '(not used)'}
                </Table.Cell>
                <Table.Cell
                  textAlign="center"
                  verticalAlign="middle"
                >
                  {actualNavigation ? (
                    <MatchedSetActionButtons
                      matchedNavigation={actualNavigation}
                      dispatchMatchState={dispatchMatchState}
                      isAttemptMode={isAttemptMappedScramble}
                    />
                  ) : (
                    <ExternalSetActionButtons
                      scrSet={scrSet}
                      autoMatchSettings={autoMatchSettings}
                      rootMatchState={matchState}
                      dispatchMatchState={dispatchMatchState}
                      fluid={false}
                    />
                  )}
                </Table.Cell>
              </Table.Row>
            );
          })}
        </Table.Body>
      </Table>
      <Button.Group widths={3}>
        <Button
          primary
          icon="magic"
          content="Auto-Assign"
          onClick={autoAssignAction}
        />
        <Button
          secondary
          icon="eraser"
          content="Clear"
          onClick={clearAllAction}
        />
        <Button
          negative
          icon="trash"
          content="Delete Upload"
          onClick={deleteAction}
          disabled={isDeleting}
          loading={isDeleting}
        />
      </Button.Group>
    </>
  );
}

export default function ScrambleFileList({
  scrambleFiles,
  autoMatchSettings,
  isFetching,
  matchState,
  dispatchMatchState,
}) {
  if (isFetching) {
    return <Loading />;
  }

  if (scrambleFiles.length === 0) {
    return null;
  }

  const panels = scrambleFiles.map((scrFile) => ({
    key: scrFile.id,
    title: {
      as: Header,
      content: <ScrambleFileHeader scrambleFile={scrFile} />,
    },
    content: {
      content: <ScrambleFileBody
        scrambleFile={scrFile}
        autoMatchSettings={autoMatchSettings}
        matchState={matchState}
        dispatchMatchState={dispatchMatchState}
      />,
    },
  }));

  return (
    <Accordion styled fluid panels={panels} />
  );
}
